schema-version = 1

[package]
title = "LogiXstream"
version = "0.1.0"
id = "com.anil.vegaott"
icon = "@image/vega.png"

[components]

[[components.interactive]]
id = "com.anil.vegaott.main"
runtime-module = "/com.amazon.kepler.keplerscript.runtime.loader_2@IKeplerScript_2_0"
launch-type = "singleton"
categories = ["com.amazon.category.main"]
icon = "@image/vega.png"

[[message]]
uri = "logixstream://home"
sender-privileges = ["*"]
receiver-privileges = ["self"]

[[message]]
uri = "logixstream://movies"
sender-privileges = ["*"]
receiver-privileges = ["self"]

[[message]]
uri = "logixstream://movie"
sender-privileges = ["*"]
receiver-privileges = ["self"]

[[message]]
uri = "logixstream://play"
sender-privileges = ["*"]
receiver-privileges = ["self"]

[[message]]
uri = "logixstream://settings"
sender-privileges = ["*"]
receiver-privileges = ["self"]

[[message]]
uri = "logixstream://profile"
sender-privileges = ["*"]
receiver-privileges = ["self"]

[[message]]
uri = "logixstream://edit-profile"
sender-privileges = ["*"]
receiver-privileges = ["self"]

[[message]]
uri = "logixstream://search"
sender-privileges = ["*"]
receiver-privileges = ["self"]

[[message]]
uri = "logixstream://movie/jawan"
sender-privileges = ["*"]
receiver-privileges = ["self"]

[[message]]
uri = "logixstream://play/jawan"
sender-privileges = ["*"]
receiver-privileges = ["self"]

[wants]

[[wants.service]]
id = "com.amazon.mediametrics.service"

[[wants.service]]
id = "com.amazon.media.server"

[[wants.service]]
id = "com.amazon.gipc.uuid.*"

[[wants.service]]
id = "com.amazon.media.playersession.service"

[[wants.service]]
id = "com.amazon.mediabuffer.service"

[[wants.service]]
id = "com.amazon.mediatransform.service"

[[wants.service]]
id = "com.amazon.audio.stream"

[[wants.service]]
id = "com.amazon.audio.control"

[[wants.service]]
id = "com.amazon.audio.system"

[[wants.service]]
id = "com.amazon.network.service"

# Required for the Vega OS on-screen keyboard used by TextInput controls.
[[wants.service]]
id = "com.amazon.inputmethod.service"

[[wants.service]]
id = "com.amazon.inputd.service"

[[wants.privilege]]
id = "com.amazon.devconf.privilege.accessibility"

[[wants.privilege]]
id = "com.amazon.network.privilege.net-info"

[offers]

[[offers.module]]
id = "/com.anil.vegaott.deeplinks@IDeeplinks"
includes-messages = [
  "logixstream://home",
  "logixstream://movies",
  "logixstream://movie",
  "logixstream://play",
  "logixstream://settings",
  "logixstream://profile",
  "logixstream://edit-profile",
  "logixstream://search",
  "logixstream://movie/jawan",
  "logixstream://play/jawan",
]

[[offers.interaction]]
id = "com.anil.vegaott.main"
launch-uris = [
  "logixstream://home",
  "logixstream://movies",
  "logixstream://search",
  "logixstream://movie/jawan",
  "logixstream://play/jawan",
  "logixstream://settings",
  "logixstream://profile",
]

[[offers.message-target]]
uris = [
  "logixstream://home",
  "logixstream://movies",
  "logixstream://movie",
  "logixstream://play",
  "logixstream://settings",
  "logixstream://profile",
  "logixstream://edit-profile",
  "logixstream://search",
  "logixstream://movie/jawan",
  "logixstream://play/jawan",
]
uses-component = "com.anil.vegaott.main"

[[offers.service]]
id = "com.amazon.gipc.uuid.*"
