import {StyleSheet} from 'react-native';
import {colors} from '../../../theme/colors';
import {fontSizes, fontWeights} from '../../../theme/fonts';
import {borderRadius, sizes, spacing} from '../../../theme/sizes';

export const styles = StyleSheet.create({
  background: {flex: 1, backgroundColor: colors.screenBackground},
  content: {
    flex: 1,
    position: 'relative',
    paddingLeft: sizes.menuWidthCollapsed,
    paddingBottom: spacing.contentBottom,
  },
  titleSection: {
    marginHorizontal: spacing.screenPadding,
    marginBottom: spacing.large,
  },
  title: {
    color: colors.textPrimary,
    fontSize: fontSizes.moviesTitle,
    fontWeight: fontWeights.bold,
  },
  subtitle: {
    color: colors.textSecondary,
    fontSize: fontSizes.body,
    marginTop: spacing.xs,
  },
  filterBar: {
    alignItems: 'flex-end',
    marginHorizontal: spacing.screenPadding,
    marginBottom: spacing.md,
  },
  filterButton: {
    minWidth: 180,
    paddingHorizontal: spacing.xl,
    paddingVertical: spacing.md,
    borderWidth: spacing.borderMedium,
    borderColor: colors.cardBorder,
    borderRadius: borderRadius.sm,
    backgroundColor: colors.darkCardBackground,
  },
  filterButtonSelected: {backgroundColor: colors.heroAccent},
  filterButtonFocused: {borderColor: colors.focusRing},
  filterButtonText: {
    color: colors.textPrimary,
    fontSize: fontSizes.button,
    fontWeight: fontWeights.bold,
    textAlign: 'center',
  },
  guide: {
    flex: 1,
    position: 'relative',
  },
  epg: {flex: 1},
  loadingOverlay: {
    ...StyleSheet.absoluteFillObject,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.screenBackground,
  },
  emptyChannelOverlay: {
    ...StyleSheet.absoluteFillObject,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.darkOverlay,
  },
  emptyChannelText: {
    color: colors.textPrimary,
    fontSize: fontSizes.subheading,
    fontWeight: fontWeights.semibold,
  },
  emptyChannelButton: {
    minWidth: 220,
    marginTop: spacing.huge,
    paddingHorizontal: spacing.huge,
    paddingVertical: spacing.xl,
    borderWidth: spacing.borderThick,
    borderColor: colors.focusRing,
    borderRadius: borderRadius.sm,
    backgroundColor: colors.heroAccent,
  },
  emptyChannelButtonText: {
    color: colors.textPrimary,
    fontSize: fontSizes.button,
    fontWeight: fontWeights.bold,
    textAlign: 'center',
  },
  paginationLoaderOverlay: {
    position: 'absolute',
    top: 0,
    right: 0,
    bottom: 0,
    left: sizes.menuWidthCollapsed,
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 1000,
    elevation: 1000,
  },
  paginationLoader: {
    width: 88,
    height: 88,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: borderRadius.circle,
    borderWidth: spacing.borderThin,
    borderColor: colors.borderLight,
    backgroundColor: colors.detailOverlay,
  },
  details: {
    minHeight: 126,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginHorizontal: spacing.screenPadding,
    marginTop: spacing.large,
    paddingHorizontal: spacing.huge,
    paddingVertical: spacing.xl,
    borderWidth: spacing.borderThin,
    borderColor: colors.cardBorder,
    borderRadius: borderRadius.md,
    backgroundColor: colors.detailOverlay,
  },
  detailsImage: {
    // width: 152,
    // height: 86,
    width: 352,
    height: 286,
    marginRight: spacing.huge,
    borderRadius: borderRadius.sm,
    backgroundColor: colors.cardBackground,
  },
  detailsText: {flex: 1, marginRight: spacing.huge},
  detailsTitle: {
    color: colors.textPrimary,
    fontSize: fontSizes.rowTitle,
    fontWeight: fontWeights.bold,
  },
  detailsTime: {
    color: colors.focusedTint,
    fontSize: fontSizes.body,
    fontWeight: fontWeights.semibold,
    marginTop: spacing.xs,
  },
  detailsDescription: {
    color: colors.textSecondary,
    fontSize: fontSizes.castLabel,
    marginTop: spacing.md,
  },
  detailsLive: {
    color: colors.success,
    fontSize: fontSizes.button,
    fontWeight: fontWeights.bold,
  },
  emptyDetails: {color: colors.textSecondary, fontSize: fontSizes.body},
  alertBackdrop: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.darkOverlay,
  },
  categoryMenuBackdrop: {
    flex: 1,
    alignItems: 'flex-end',
    justifyContent: 'flex-start',
    paddingTop: 170,
    paddingRight: spacing.screenPadding,
    backgroundColor: colors.darkOverlay,
  },
  categoryMenu: {
    width: 300,
    paddingVertical: spacing.sm,
    borderWidth: spacing.borderMedium,
    borderColor: colors.borderLight,
    borderRadius: borderRadius.md,
    backgroundColor: colors.darkCardBackground,
  },
  categoryOption: {
    paddingHorizontal: spacing.xl,
    paddingVertical: spacing.md,
  },
  filterDivider: {
    height: spacing.borderThin,
    marginVertical: spacing.sm,
    backgroundColor: colors.cardBorder,
  },
  categoryOptionSelected: {backgroundColor: colors.heroAccent},
  categoryOptionText: {
    color: colors.textPrimary,
    fontSize: fontSizes.button,
    fontWeight: fontWeights.semibold,
  },
  alertCard: {
    width: 560,
    padding: spacing.colossal,
    borderWidth: spacing.borderMedium,
    borderColor: colors.borderLight,
    borderRadius: borderRadius.lg,
    backgroundColor: colors.darkCardBackground,
  },
  alertTitle: {
    color: colors.textPrimary,
    fontSize: fontSizes.rowTitle,
    fontWeight: fontWeights.bold,
  },
  alertMessage: {
    color: colors.textSecondary,
    fontSize: fontSizes.subheading,
    marginTop: spacing.md,
  },
  alertButton: {
    alignSelf: 'flex-end',
    minWidth: 132,
    marginTop: spacing.huge,
    paddingHorizontal: spacing.huge,
    paddingVertical: spacing.xl,
    borderWidth: spacing.borderThick,
    borderColor: colors.focusRing,
    borderRadius: borderRadius.sm,
    backgroundColor: colors.heroAccent,
  },
  alertButtonText: {
    color: colors.textPrimary,
    fontSize: fontSizes.button,
    fontWeight: fontWeights.bold,
    textAlign: 'center',
  },
});
