import {StyleSheet} from 'react-native';
import {colors} from '../theme/colors';
import {fontSizes, fontWeights} from '../theme/fonts';
import {borderRadius, sizes, spacing} from '../theme/sizes';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    paddingHorizontal: spacing.screenHorizontal,
    paddingTop: spacing.xlarge,
    alignItems: 'center',
  },
  card: {
    flex: 1,
    width: '100%',
    maxWidth: sizes.tvAccountMaxWidth,
    flexDirection: 'row',
    backgroundColor: colors.darkCardBackground,
    borderRadius: borderRadius.card,
    borderWidth: spacing.borderMedium,
    borderColor: colors.cardBorder,
    overflow: 'hidden',
    shadowColor: colors.shadowDark,
    shadowOffset: {width: 0, height: spacing.xxl},
    shadowOpacity: 0.55,
    shadowRadius: spacing.colossal,
  },
  avatarPanel: {
    width: '34%',
    padding: spacing.giant,
    alignItems: 'center',
    backgroundColor: colors.cardOverlay,
    borderRightWidth: spacing.borderThin,
    borderRightColor: colors.cardBorder,
  },
  avatarHeading: {
    width: '100%',
    marginBottom: spacing.xl,
  },
  sectionTitle: {
    color: colors.textPrimary,
    fontSize: fontSizes.subheading,
    fontWeight: fontWeights.bold,
  },
  sectionHint: {
    color: colors.textSecondary,
    fontSize: fontSizes.small,
    marginTop: spacing.xs,
  },
  previewName: {
    color: colors.textPrimary,
    fontSize: fontSizes.subheading,
    fontWeight: fontWeights.bold,
    maxWidth: '100%',
    marginTop: spacing.xl,
  },
  previewLabel: {
    color: colors.textSecondary,
    fontSize: fontSizes.small,
    marginTop: spacing.xs,
  },
  avatarGrid: {
    width: '100%',
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    marginTop: spacing.xlarge,
  },
  avatarOption: {
    width: '48%',
    minHeight: sizes.settingsAvatarOptionMinHeight,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: spacing.xl,
    marginBottom: spacing.xl,
    borderRadius: borderRadius.xl,
    backgroundColor: colors.inputBackground,
    borderWidth: spacing.borderHeavy,
    borderColor: colors.transparent,
  },
  avatarOptionSelected: {
    backgroundColor: colors.inputFocusedBackground,
    borderColor: colors.cardBorder,
  },
  avatarColor: {
    width: spacing.xlarge,
    height: spacing.xlarge,
    borderRadius: borderRadius.circle,
    marginRight: spacing.lg,
  },
  avatarOptionText: {
    flex: 1,
    color: colors.textPrimary,
    fontSize: fontSizes.small,
    fontWeight: fontWeights.semibold,
  },
  selectionDot: {
    width: spacing.xl,
    height: spacing.xl,
    borderRadius: borderRadius.circle,
    borderWidth: spacing.borderThick,
    borderColor: colors.textSecondary,
  },
  selectionDotSelected: {
    borderColor: colors.textPrimary,
    backgroundColor: colors.heroAccent,
  },
  editorPanel: {
    flex: 1,
    padding: spacing.giant,
  },
  editorHeading: {
    minHeight: sizes.settingsEditorMinHeight,
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    marginBottom: spacing.xl,
  },
  errorText: {
    maxWidth: '48%',
    color: colors.errorText,
    fontSize: fontSizes.small,
    paddingHorizontal: spacing.xl,
    paddingVertical: spacing.md,
    borderRadius: borderRadius.md,
    backgroundColor: colors.errorBackground,
  },
  formRow: {
    flexDirection: 'row',
    marginHorizontal: -spacing.md,
    marginBottom: spacing.xl,
  },
  fieldGroup: {
    flex: 1,
    marginHorizontal: spacing.md,
  },
  label: {
    color: colors.textSecondary,
    fontSize: fontSizes.small,
    fontWeight: fontWeights.semibold,
    marginBottom: spacing.md,
  },
  input: {
    minHeight: sizes.settingsReadOnlyMinHeight,
    color: colors.textPrimary,
    fontSize: fontSizes.body,
    paddingHorizontal: spacing.xlarge,
    paddingVertical: spacing.xl,
    borderRadius: borderRadius.xl,
    backgroundColor: colors.inputBackground,
    borderWidth: spacing.borderHeavy,
    borderColor: colors.transparent,
  },
  inputFocused: {
    borderColor: colors.focusRing,
    backgroundColor: colors.inputFocusedBackground,
    shadowColor: colors.focusRing,
    shadowOffset: {width: 0, height: 0},
    shadowOpacity: 0.55,
    shadowRadius: spacing.lg,
  },
  readOnlyField: {
    minHeight: sizes.settingsReadOnlyMinHeight,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: spacing.xlarge,
    borderRadius: borderRadius.xl,
    backgroundColor: colors.cardHoverBackground,
    borderWidth: spacing.borderThin,
    borderColor: colors.cardBorderLight,
  },
  readOnlyText: {
    flex: 1,
    color: colors.textSecondary,
    fontSize: fontSizes.body,
  },
  lockedLabel: {
    color: colors.textSecondary,
    fontSize: fontSizes.small,
    fontWeight: fontWeights.bold,
    marginLeft: spacing.xl,
    textTransform: 'uppercase',
    letterSpacing: 0.6,
  },
  divider: {
    height: 1,
    backgroundColor: colors.cardBorder,
    marginTop: spacing.xxs,
    marginBottom: spacing.xl,
  },
  groupLabel: {
    color: colors.textSecondary,
    fontSize: fontSizes.small,
    fontWeight: fontWeights.bold,
    textTransform: 'uppercase',
    letterSpacing: 1,
    marginBottom: spacing.md,
  },
  themeRow: {
    flexDirection: 'row',
    marginHorizontal: -spacing.md,
    marginBottom: spacing.xl,
  },
  themeOption: {
    flex: 1,
    minHeight: sizes.settingsAvatarOptionMinHeight,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: spacing.xl,
    marginHorizontal: spacing.md,
    borderRadius: borderRadius.xl,
    backgroundColor: colors.cardHoverBackground,
    borderWidth: spacing.borderHeavy,
    borderColor: colors.transparent,
  },
  themeOptionSelected: {
    backgroundColor: colors.inputFocusedBackground,
    borderColor: colors.cardBorder,
  },
  themeColor: {
    width: spacing.xlarge,
    height: spacing.section,
    borderRadius: borderRadius.circle,
    marginRight: spacing.xl,
  },
  themeOptionText: {
    color: colors.textPrimary,
    fontSize: fontSizes.small,
    fontWeight: fontWeights.bold,
  },
  toggleRow: {
    flexDirection: 'row',
    marginHorizontal: -spacing.md,
    marginBottom: spacing.xl,
  },
  toggleCard: {
    flex: 1,
    minHeight: sizes.settingsToggleCardAltMinHeight,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: spacing.xlarge,
    marginHorizontal: spacing.md,
    borderRadius: borderRadius.xl,
    backgroundColor: colors.cardHoverBackground,
    borderWidth: spacing.borderHeavy,
    borderColor: colors.transparent,
  },
  toggleCopy: {
    flex: 1,
    paddingRight: spacing.xl,
  },
  toggleLabel: {
    color: colors.textPrimary,
    fontSize: fontSizes.body,
    fontWeight: fontWeights.bold,
  },
  toggleHint: {
    color: colors.textSecondary,
    fontSize: fontSizes.small,
    marginTop: spacing.xs,
  },
  switchTrack: {
    width: sizes.profileMinSwitchWidth,
    height: sizes.profileMinSwitchHeight,
    justifyContent: 'center',
    paddingHorizontal: spacing.xs,
    borderRadius: borderRadius.circle,
    backgroundColor: colors.actionSecondary,
  },
  switchTrackEnabled: {
    backgroundColor: colors.success,
  },
  switchThumb: {
    width: sizes.settingsSwitchThumbCompactSize,
    height: sizes.settingsSwitchThumbCompactSize,
    borderRadius: borderRadius.circle,
    backgroundColor: colors.textPrimary,
  },
  switchThumbEnabled: {
    alignSelf: 'flex-end',
  },
  actionRow: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    marginTop: 'auto',
  },
  cancelButton: {
    minWidth: sizes.settingsCancelButtonMinWidth,
    minHeight: sizes.profileCardMinHeight,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: spacing.xlarge,
    marginRight: spacing.xl,
    borderRadius: borderRadius.xl,
    backgroundColor: colors.inputBackground,
    borderWidth: spacing.borderHeavy,
    borderColor: colors.transparent,
  },
  cancelButtonText: {
    color: colors.textPrimary,
    fontSize: fontSizes.body,
    fontWeight: fontWeights.bold,
  },
  saveButton: {
    minWidth: sizes.settingsSaveButtonMinWidth,
    minHeight: sizes.profileCardMinHeight,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: spacing.xlarge,
    borderRadius: borderRadius.xl,
    backgroundColor: colors.heroAccent,
    borderWidth: spacing.borderHeavy,
    borderColor: colors.transparent,
  },
  saveButtonText: {
    color: colors.textPrimary,
    fontSize: fontSizes.body,
    fontWeight: fontWeights.bold,
  },
  controlFocused: {
    borderColor: colors.focusRing,
    backgroundColor: colors.inputFocusedBackground,
    transform: [{scale: 1.025}],
    shadowColor: colors.focusRing,
    shadowOffset: {width: 0, height: 0},
    shadowOpacity: 0.7,
    shadowRadius: spacing.xl,
  },
  controlDisabled: {
    opacity: 0.55,
  },
});
