import {StyleSheet} from 'react-native';
import {colors} from '../theme/colors';
import {fontSizes, fontWeights} from '../theme/fonts';
import {borderRadius, sizes, spacing} from '../theme/sizes';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    paddingHorizontal: spacing.screenHorizontal,
    paddingTop: spacing.xlarge,
    alignItems: 'center',
  },
  card: {
    flex: 1,
    width: '100%',
    maxWidth: sizes.tvAccountMaxWidth,
    flexDirection: 'row',
    backgroundColor: colors.darkCardBackground,
    borderRadius: borderRadius.card,
    borderWidth: spacing.borderMedium,
    borderColor: colors.cardBorder,
    overflow: 'hidden',
    shadowColor: colors.shadowDark,
    shadowOffset: {width: 0, height: spacing.xxl},
    shadowOpacity: 0.55,
    shadowRadius: spacing.colossal,
  },
  identityPanel: {
    width: '36%',
    padding: spacing.section,
    backgroundColor: colors.cardOverlay,
    borderRightWidth: spacing.borderThin,
    borderRightColor: colors.cardBorder,
    alignItems: 'center',
  },
  panelEyebrowRow: {
    width: '100%',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: spacing.xlarge,
  },
  panelEyebrow: {
    color: colors.textSecondary,
    fontSize: fontSizes.small,
    fontWeight: fontWeights.bold,
    textTransform: 'uppercase',
    letterSpacing: 1.2,
  },
  readyBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: spacing.xl,
    paddingVertical: spacing.sm,
    borderRadius: borderRadius.circle,
    backgroundColor: colors.inputBackground,
  },
  readyDot: {
    width: spacing.md,
    height: spacing.md,
    borderRadius: borderRadius.circle,
    marginRight: spacing.md,
    backgroundColor: colors.success,
  },
  readyText: {
    color: colors.textPrimary,
    fontSize: fontSizes.small,
    fontWeight: fontWeights.semibold,
  },
  userName: {
    color: colors.textPrimary,
    fontSize: fontSizes.avatar,
    fontWeight: fontWeights.bold,
    marginTop: spacing.xlarge,
    maxWidth: '100%',
  },
  userEmail: {
    color: colors.textSecondary,
    fontSize: fontSizes.body,
    marginTop: spacing.sm,
    maxWidth: '100%',
  },
  membershipCard: {
    width: '100%',
    minHeight: sizes.profileMembershipCardMinHeight,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: spacing.xlarge,
    marginTop: spacing.xlarge,
    borderRadius: borderRadius.xl,
    backgroundColor: colors.inputBackground,
    borderWidth: spacing.borderThin,
    borderColor: colors.cardBorder,
  },
  membershipLabel: {
    color: colors.textSecondary,
    fontSize: fontSizes.small,
    textTransform: 'uppercase',
    letterSpacing: 0.8,
  },
  membershipValue: {
    color: colors.textPrimary,
    fontSize: fontSizes.cardTitle,
    fontWeight: fontWeights.bold,
    marginTop: spacing.xs,
  },
  membershipQuality: {
    color: colors.textPrimary,
    fontSize: fontSizes.small,
    fontWeight: fontWeights.black,
    paddingHorizontal: spacing.xl,
    paddingVertical: spacing.md,
    borderRadius: borderRadius.md,
    backgroundColor: colors.heroAccent,
  },
  editButton: {
    width: '100%',
    minHeight: sizes.profileActionMinHeight,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: spacing.xlarge,
    marginTop: 'auto',
    borderRadius: borderRadius.xl,
    backgroundColor: colors.heroAccent,
    borderWidth: spacing.borderHeavy,
    borderColor: colors.transparent,
  },
  editButtonFocused: {
    borderColor: colors.focusRing,
    backgroundColor: colors.logoutButtonFocused,
    transform: [{scale: 1.025}],
    shadowColor: colors.focusRing,
    shadowOffset: {width: 0, height: 0},
    shadowOpacity: 0.7,
    shadowRadius: spacing.xl,
  },
  editButtonText: {
    color: colors.textPrimary,
    fontSize: fontSizes.button,
    fontWeight: fontWeights.bold,
  },
  editButtonArrow: {
    color: colors.textPrimary,
    fontSize: fontSizes.userName,
    fontWeight: fontWeights.regular,
  },
  contentPanel: {
    flex: 1,
    padding: spacing.section,
  },
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: spacing.xlarge,
  },
  sectionTitle: {
    color: colors.textPrimary,
    fontSize: fontSizes.subheading,
    fontWeight: fontWeights.bold,
  },
  sectionHint: {
    color: colors.textSecondary,
    fontSize: fontSizes.caption,
    marginTop: spacing.xs,
  },
  avatarNameBadge: {
    paddingHorizontal: spacing.xlarge,
    paddingVertical: spacing.md,
    borderRadius: borderRadius.circle,
    backgroundColor: colors.inputBackground,
    borderWidth: spacing.borderThin,
    borderColor: colors.cardBorder,
  },
  avatarNameBadgeText: {
    color: colors.textPrimary,
    fontSize: fontSizes.caption,
    fontWeight: fontWeights.semibold,
  },
  detailsGrid: {
    flexDirection: 'row',
    marginHorizontal: -spacing.md,
  },
  detailTile: {
    flex: 1,
    minHeight: sizes.profileDetailTileMinHeight,
    justifyContent: 'center',
    paddingHorizontal: spacing.xlarge,
    marginHorizontal: spacing.md,
    borderRadius: borderRadius.xl,
    backgroundColor: colors.cardHoverBackground,
    borderWidth: spacing.borderThin,
    borderColor: colors.cardBorderLight,
  },
  detailLabel: {
    color: colors.textSecondary,
    fontSize: fontSizes.caption,
  },
  detailValue: {
    color: colors.textPrimary,
    fontSize: fontSizes.cardTitle,
    fontWeight: fontWeights.bold,
    marginTop: spacing.sm,
    textTransform: 'capitalize',
  },
  divider: {
    height: 1,
    backgroundColor: colors.cardBorder,
    marginVertical: spacing.huge,
  },
  preferencesList: {
    flex: 1,
    justifyContent: 'space-between',
  },
  preferenceRow: {
    minHeight: sizes.profilePreferenceMinHeight,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: spacing.xlarge,
    borderRadius: borderRadius.xl,
    backgroundColor: colors.cardHoverBackground,
    borderWidth: spacing.borderThin,
    borderColor: colors.cardBorderLight,
  },
  preferenceIcon: {
    width: spacing.section,
    height: spacing.section,
    borderRadius: borderRadius.circle,
    borderWidth: spacing.borderThin,
    borderColor: colors.cardBorder,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: spacing.xlarge,
  },
  preferenceIconDot: {
    width: spacing.xl,
    height: spacing.xl,
    borderRadius: borderRadius.circle,
    backgroundColor: colors.success,
  },
  preferenceIconDotDisabled: {
    backgroundColor: colors.textSecondary,
    opacity: 0.45,
  },
  preferenceCopy: {
    flex: 1,
  },
  preferenceLabel: {
    color: colors.textPrimary,
    fontSize: fontSizes.body,
    fontWeight: fontWeights.bold,
  },
  preferenceHint: {
    color: colors.textSecondary,
    fontSize: fontSizes.small,
    marginTop: spacing.xs,
  },
  valuePill: {
    minWidth: sizes.profileValuePillMinWidth,
    alignItems: 'center',
    paddingHorizontal: spacing.xl,
    paddingVertical: spacing.md,
    borderRadius: borderRadius.circle,
    backgroundColor: colors.inputBackground,
  },
  valuePillEnabled: {
    backgroundColor: `${colors.success}2E`,
  },
  valuePillText: {
    color: colors.textPrimary,
    fontSize: fontSizes.caption,
    fontWeight: fontWeights.bold,
  },
});
