import {StyleSheet} from 'react-native';
import {colors} from '../theme/colors';
import {fontSizes, fontWeights} from '../theme/fonts';
import {borderRadius, sizes, spacing} from '../theme/sizes';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    paddingHorizontal: spacing.heroContentPadding,
    paddingTop: spacing.lg,
    justifyContent: 'center',
    alignItems: 'center',
  },
  card: {
    backgroundColor: colors.darkCardBackground,
    borderRadius: borderRadius.card,
    padding: spacing.cardPadding,
    borderWidth: 1.5,
    borderColor: colors.cardBorder,
    maxWidth: sizes.settingsCardMaxWidth,
    marginTop: spacing.md,
    shadowColor: colors.shadowDark,
    shadowOffset: {width: spacing.none, height: spacing.xxl},
    shadowOpacity: 0.6,
    shadowRadius: spacing.colossal,
  },
  headerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: spacing.giant,
  },
  avatarBadge: {
    width: sizes.avatarSize,
    height: sizes.avatarSize,
    borderRadius: sizes.avatarRadius,
    backgroundColor: colors.heroAccent,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: spacing.huge,
    borderWidth: 3,
    borderColor: colors.borderLight,
    shadowColor: colors.heroAccent,
    shadowOffset: {width: spacing.none, height: spacing.xs},
    shadowOpacity: 0.4,
    shadowRadius: spacing.xl,
  },
  avatarText: {
    color: colors.textPrimary,
    fontSize: fontSizes.avatar,
    fontWeight: fontWeights.black,
  },
  userName: {
    color: colors.textPrimary,
    fontSize: fontSizes.userName,
    fontWeight: fontWeights.bold,
    letterSpacing: 0.5,
  },
  userEmail: {
    color: colors.textPrimary,
    opacity: 0.65,
    fontSize: fontSizes.body,
    marginTop: spacing.xs,
  },
  detailsContainer: {
    borderTopWidth: 1,
    borderTopColor: colors.cardBorderLight,
    paddingTop: spacing.huge,
    marginBottom: spacing.giant,
  },
  infoRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: spacing.xxl,
    paddingHorizontal: spacing.xlarge,
    backgroundColor: colors.cardHoverBackground,
    borderRadius: borderRadius.lg,
    marginBottom: spacing.lg,
    borderWidth: 1,
    borderColor: colors.cardBorderLight,
  },
  infoLabel: {
    color: colors.textPrimary,
    opacity: 0.55,
    fontSize: fontSizes.label,
    fontWeight: fontWeights.semibold,
  },
  infoValue: {
    color: colors.textPrimary,
    fontWeight: fontWeights.bold,
    fontSize: fontSizes.body,
  },
  infoValueSmall: {
    fontSize: fontSizes.small,
    opacity: 0.75,
    paddingLeft: spacing.giant,
  },
  subBadge: {
    backgroundColor: colors.heroAccent,
    paddingHorizontal: spacing.large,
    paddingVertical: spacing.sm,
    borderRadius: borderRadius.xxl,
    shadowColor: colors.heroAccent,
    shadowOffset: {width: spacing.none, height: spacing.xxs},
    shadowOpacity: 0.5,
    shadowRadius: spacing.md,
  },
  subBadgeText: {
    color: colors.textPrimary,
    fontWeight: fontWeights.bold,
    fontSize: fontSizes.small,
    letterSpacing: 0.8,
    textTransform: 'uppercase',
  },
  logoutButton: {
    backgroundColor: colors.logoutButtonBackground,
    borderRadius: borderRadius.xl,
    paddingVertical: spacing.large,
    alignItems: 'center',
    marginTop: spacing.xl,
    borderWidth: 2,
    borderColor: colors.logoutButtonBorder,
  },
  logoutButtonFocused: {
    borderColor: colors.textPrimary,
    borderWidth: 3,
    backgroundColor: colors.logoutButtonFocused,
    transform: [{scale: 1.04}],
    shadowColor: colors.textPrimary,
    shadowOffset: {width: spacing.none, height: spacing.none},
    shadowOpacity: 0.8,
    shadowRadius: spacing.xxl,
  },
  logoutButtonText: {
    color: colors.textPrimary,
    fontSize: fontSizes.button,
    fontWeight: fontWeights.bold,
    letterSpacing: 0.5,
  },
  authActionRow: {
    flexDirection: 'row',
    marginTop: spacing.giant,
  },
  authBtn: {
    flex: 1,
    backgroundColor: '#FFFFFF',
    borderRadius: borderRadius.xl,
    paddingVertical: spacing.large,
    alignItems: 'center',
    marginRight: spacing.xxxl,
    borderWidth: 2.5,
    borderColor: colors.transparent,
  },
  authBtnSecondary: {
    backgroundColor: '#BFA24A',
    borderWidth: 1.5,
    borderColor: colors.borderLight,
  },
  authBtnFocused: {
    borderColor: colors.textPrimary,
    borderWidth: 3,
    backgroundColor: colors.logoutButtonFocused,
    transform: [{scale: 1.05}],
    shadowColor: colors.textPrimary,
    shadowOffset: {width: spacing.none, height: spacing.none},
    shadowOpacity: 0.8,
    shadowRadius: spacing.xxl,
  },
  authBtnText: {
    color: colors.actionPrimaryText,
    fontSize: fontSizes.button,
    fontWeight: fontWeights.bold,
    letterSpacing: 0.5,
  },
});
