import {StyleSheet} from 'react-native';
import {colors} from '../theme/colors';
import {fontSizes, fontWeights} from '../theme/fonts';
import {borderRadius, sizes, spacing} from '../theme/sizes';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    paddingHorizontal: spacing.screenHorizontal,
    paddingTop: spacing.xlarge,
    alignItems: 'center',
  },
  card: {
    flex: 1,
    width: '100%',
    maxWidth: sizes.tvAccountMaxWidth,
    flexDirection: 'row',
    backgroundColor: colors.darkCardBackground,
    borderRadius: borderRadius.card,
    borderWidth: spacing.borderMedium,
    borderColor: colors.cardBorder,
    overflow: 'hidden',
    shadowColor: colors.shadowDark,
    shadowOffset: {width: 0, height: spacing.xxl},
    shadowOpacity: 0.55,
    shadowRadius: spacing.colossal,
  },
  accountPanel: {
    width: '36%',
    padding: spacing.section,
    backgroundColor: colors.cardOverlay,
    borderRightWidth: spacing.borderThin,
    borderRightColor: colors.cardBorder,
  },
  accountHeader: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  accountHeaderCopy: {
    flex: 1,
    marginLeft: spacing.xlarge,
  },
  userName: {
    color: colors.textPrimary,
    fontSize: fontSizes.userName,
    fontWeight: fontWeights.bold,
  },
  userEmail: {
    color: colors.textSecondary,
    fontSize: fontSizes.caption,
    marginTop: spacing.sm,
  },
  planRow: {
    minHeight: sizes.settingsPlanMinHeight,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: spacing.xlarge,
    marginTop: spacing.xlarge,
    borderRadius: borderRadius.xl,
    backgroundColor: colors.inputBackground,
    borderWidth: spacing.borderThin,
    borderColor: colors.cardBorder,
  },
  planValue: {
    color: colors.textPrimary,
    fontSize: fontSizes.cardTitle,
    fontWeight: fontWeights.bold,
    marginTop: spacing.xs,
  },
  planBadge: {
    paddingHorizontal: spacing.xl,
    paddingVertical: spacing.md,
    borderRadius: borderRadius.md,
    backgroundColor: colors.heroAccent,
  },
  planBadgeText: {
    color: colors.textPrimary,
    fontSize: fontSizes.small,
    fontWeight: fontWeights.black,
  },
  locationRow: {
    flexDirection: 'row',
    marginTop: spacing.xlarge,
    marginHorizontal: -spacing.md,
  },
  locationItem: {
    flex: 1,
    minWidth: 0,
    marginHorizontal: spacing.md,
  },
  metaLabel: {
    color: colors.textSecondary,
    fontSize: fontSizes.small,
    textTransform: 'uppercase',
    letterSpacing: 0.7,
  },
  metaValue: {
    color: colors.textPrimary,
    fontSize: fontSizes.body,
    fontWeight: fontWeights.semibold,
    marginTop: spacing.sm,
    textTransform: 'capitalize',
  },
  accountActions: {
    marginTop: spacing.xlarge,
  },
  accountFooter: {
    marginTop: 'auto',
  },
  actionButton: {
    minHeight: sizes.settingsActionMinHeight,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: spacing.xlarge,
    marginBottom: spacing.xl,
    borderRadius: borderRadius.xl,
    backgroundColor: colors.inputBackground,
    borderWidth: spacing.borderHeavy,
    borderColor: colors.transparent,
  },
  actionButtonDestructive: {
    backgroundColor: colors.logoutButtonBackground,
    borderColor: colors.logoutButtonBorder,
  },
  actionCopy: {
    flex: 1,
  },
  actionLabel: {
    color: colors.textPrimary,
    fontSize: fontSizes.body,
    fontWeight: fontWeights.bold,
  },
  actionHint: {
    color: colors.textSecondary,
    fontSize: fontSizes.small,
    marginTop: spacing.xs,
  },
  actionArrow: {
    color: colors.textPrimary,
    fontSize: fontSizes.subheading,
  },
  preferencesPanel: {
    flex: 1,
    padding: spacing.section,
  },
  sectionHeading: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: spacing.huge,
  },
  sectionTitle: {
    color: colors.textPrimary,
    fontSize: fontSizes.subheading,
    fontWeight: fontWeights.bold,
  },
  sectionHint: {
    color: colors.textSecondary,
    fontSize: fontSizes.caption,
    marginTop: spacing.xs,
  },
  saveStatus: {
    color: colors.textSecondary,
    fontSize: fontSizes.small,
    fontWeight: fontWeights.semibold,
    paddingHorizontal: spacing.xl,
    paddingVertical: spacing.md,
    borderRadius: borderRadius.circle,
    backgroundColor: colors.inputBackground,
  },
  groupLabel: {
    color: colors.textSecondary,
    fontSize: fontSizes.small,
    fontWeight: fontWeights.bold,
    textTransform: 'uppercase',
    letterSpacing: 1,
    marginBottom: spacing.xl,
  },
  themeRow: {
    flexDirection: 'row',
    marginHorizontal: -spacing.md,
  },
  themeCard: {
    flex: 1,
    minHeight: sizes.settingsThemeCardMinHeight,
    padding: spacing.xlarge,
    marginHorizontal: spacing.md,
    borderRadius: borderRadius.xl,
    backgroundColor: colors.cardHoverBackground,
    borderWidth: spacing.borderHeavy,
    borderColor: colors.transparent,
  },
  themeCardSelected: {
    backgroundColor: colors.inputBackground,
    borderColor: colors.cardBorder,
  },
  themeSwatch: {
    width: sizes.settingsThemeSwatchWidth,
    height: sizes.settingsThemeSwatchHeight,
    borderRadius: borderRadius.circle,
    marginBottom: spacing.xl,
  },
  themeName: {
    color: colors.textPrimary,
    fontSize: fontSizes.body,
    fontWeight: fontWeights.bold,
  },
  themeHint: {
    color: colors.textSecondary,
    fontSize: fontSizes.small,
    marginTop: spacing.xs,
  },
  themeState: {
    color: colors.textSecondary,
    fontSize: fontSizes.small,
    fontWeight: fontWeights.semibold,
    marginTop: spacing.xl,
  },
  themeStateSelected: {
    color: colors.textPrimary,
  },
  divider: {
    height: 1,
    backgroundColor: colors.cardBorder,
    marginVertical: spacing.huge,
  },
  toggleRow: {
    flexDirection: 'row',
    marginHorizontal: -spacing.md,
  },
  toggleCard: {
    flex: 1,
    minHeight: sizes.settingsToggleCardMinHeight,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: spacing.xlarge,
    marginHorizontal: spacing.md,
    borderRadius: borderRadius.xl,
    backgroundColor: colors.cardHoverBackground,
    borderWidth: spacing.borderHeavy,
    borderColor: colors.transparent,
  },
  toggleCopy: {
    flex: 1,
    paddingRight: spacing.xlarge,
  },
  toggleLabel: {
    color: colors.textPrimary,
    fontSize: fontSizes.body,
    fontWeight: fontWeights.bold,
  },
  toggleHint: {
    color: colors.textSecondary,
    fontSize: fontSizes.small,
    marginTop: spacing.xs,
  },
  switchTrack: {
    width: sizes.settingsSwitchTrackWidth,
    height: sizes.settingsSwitchTrackHeight,
    borderRadius: borderRadius.circle,
    justifyContent: 'center',
    paddingHorizontal: spacing.xs,
    backgroundColor: colors.actionSecondary,
  },
  switchTrackEnabled: {
    backgroundColor: colors.success,
  },
  switchThumb: {
    width: sizes.settingsSwitchThumbSize,
    height: sizes.settingsSwitchThumbSize,
    borderRadius: borderRadius.circle,
    backgroundColor: colors.textPrimary,
  },
  switchThumbEnabled: {
    alignSelf: 'flex-end',
  },
  focusedControl: {
    borderColor: colors.focusRing,
    backgroundColor: colors.inputFocusedBackground,
    transform: [{scale: 1.025}],
    shadowColor: colors.focusRing,
    shadowOffset: {width: 0, height: 0},
    shadowOpacity: 0.7,
    shadowRadius: spacing.xl,
  },
  controlDisabled: {
    opacity: 0.55,
  },
  remoteHint: {
    color: colors.textSecondary,
    fontSize: fontSizes.small,
    marginTop: 'auto',
  },
  preferenceError: {
    color: colors.errorText,
    fontSize: fontSizes.small,
    marginTop: 'auto',
  },
  signedOutCard: {
    width: '100%',
    maxWidth: sizes.settingsCardMaxWidth,
    padding: spacing.extraHuge,
    borderRadius: borderRadius.card,
    backgroundColor: colors.darkCardBackground,
    borderWidth: spacing.borderMedium,
    borderColor: colors.cardBorder,
  },
  signedOutTitle: {
    color: colors.textPrimary,
    fontSize: fontSizes.avatar,
    fontWeight: fontWeights.bold,
  },
  signedOutSubtitle: {
    color: colors.textSecondary,
    fontSize: fontSizes.body,
    lineHeight: fontSizes.subheading,
    marginTop: spacing.xl,
  },
  signedOutActions: {
    flexDirection: 'row',
    marginTop: spacing.section,
    marginHorizontal: -spacing.md,
  },
  authButton: {
    flex: 1,
    minHeight: sizes.settingsActionMinHeight,
    alignItems: 'center',
    justifyContent: 'center',
    marginHorizontal: spacing.md,
    borderRadius: borderRadius.xl,
    backgroundColor: colors.heroAccent,
    borderWidth: spacing.borderHeavy,
    borderColor: colors.transparent,
  },
  authButtonSecondary: {
    backgroundColor: colors.inputBackground,
  },
  authButtonText: {
    color: colors.textPrimary,
    fontSize: fontSizes.button,
    fontWeight: fontWeights.bold,
  },
});
