import {StyleSheet} from 'react-native';
import {colors} from '../theme/colors';
import {fontSizes, fontWeights} from '../theme/fonts';
import {spacing} from '../theme/sizes';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#000000',
  },
  backdropPoster: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: '#000000',
    zIndex: 0,
  },
  backdropImageStyle: {
    opacity: 0.5,
  },
  videoSurface: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'transparent',
    zIndex: 1,
  },
  overlayContainer: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(0, 0, 0, 0.45)',
    justifyContent: 'space-between',
    paddingHorizontal: spacing.huge,
    paddingVertical: spacing.huge,
    zIndex: 10,
  },
  topHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingTop: spacing.lg,
  },
  backButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.18)',
    borderRadius: spacing.xl,
    paddingHorizontal: spacing.xxxl,
    paddingVertical: spacing.lg,
    borderWidth: 1.5,
    borderColor: 'rgba(255, 255, 255, 0.3)',
    marginRight: spacing.huge,
  },
  backButtonFocused: {
    backgroundColor: colors.heroAccent,
    borderColor: colors.focusRing,
    borderWidth: 2.5,
    transform: [{scale: 1.05}],
  },
  backButtonText: {
    color: colors.textPrimary,
    fontSize: fontSizes.heroAction || 18,
    fontWeight: fontWeights.bold,
  },
  titleContainer: {
    flex: 1,
    marginLeft: spacing.lg,
  },
  movieTitle: {
    color: colors.textPrimary,
    fontSize: fontSizes.moviesTitle || 24,
    fontWeight: fontWeights.bold,
    textShadowColor: 'rgba(0, 0, 0, 0.9)',
    textShadowOffset: {width: 0, height: 2},
    textShadowRadius: 6,
  },
  movieSub: {
    color: colors.textPrimary,
    opacity: 0.8,
    fontSize: fontSizes.heroMeta || 14,
    marginTop: spacing.xs,
  },
  qualityBadge: {
    backgroundColor: 'rgba(229, 9, 20, 0.85)',
    paddingHorizontal: spacing.huge,
    paddingVertical: spacing.sm,
    borderRadius: spacing.sm,
  },
  qualityBadgeText: {
    color: colors.textPrimary,
    fontWeight: fontWeights.bold,
    fontSize: fontSizes.heroMeta || 13,
    letterSpacing: 1,
  },
  centerOverlay: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  statusText: {
    color: colors.textPrimary,
    fontSize: fontSizes.moviesTitle || 22,
    fontWeight: fontWeights.semibold,
    backgroundColor: 'rgba(0, 0, 0, 0.6)',
    paddingHorizontal: spacing.xxxl,
    paddingVertical: spacing.lg,
    borderRadius: spacing.xl,
  },
  errorOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(0, 0, 0, 0.85)',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 20,
  },
  errorCard: {
    backgroundColor: '#181818',
    borderRadius: 16,
    padding: 32,
    alignItems: 'center',
    maxWidth: 500,
    borderWidth: 1.5,
    borderColor: 'rgba(255, 255, 255, 0.2)',
  },
  errorTitle: {
    color: '#E50914',
    fontSize: 22,
    fontWeight: 'bold',
    marginBottom: 12,
  },
  errorBody: {
    color: '#FFFFFF',
    fontSize: 15,
    textAlign: 'center',
    marginBottom: 24,
    opacity: 0.9,
  },
  retryButton: {
    backgroundColor: '#E50914',
    borderRadius: 8,
    paddingHorizontal: 28,
    paddingVertical: 12,
  },
  retryButtonText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: 'bold',
  },
  bottomControls: {
    width: '100%',
    paddingBottom: spacing.lg,
  },
  progressContainer: {
    marginBottom: spacing.huge,
  },
  progressBarTrack: {
    height: 8,
    width: '100%',
    backgroundColor: 'rgba(255, 255, 255, 0.25)',
    borderRadius: 4,
    overflow: 'hidden',
  },
  progressBarFill: {
    height: '100%',
    backgroundColor: colors.heroAccent,
    borderRadius: 4,
  },
  timeRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: spacing.md,
  },
  timeText: {
    color: colors.textPrimary,
    fontSize: fontSizes.heroMeta || 14,
    fontWeight: fontWeights.semibold,
  },
  controlsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: spacing.md,
  },
  controlBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.15)',
    borderRadius: 28,
    paddingHorizontal: spacing.xxxl,
    paddingVertical: spacing.huge,
    marginHorizontal: spacing.huge,
    borderWidth: 1.5,
    borderColor: 'rgba(255, 255, 255, 0.25)',
    minWidth: 130,
  },
  playPauseBtn: {
    backgroundColor: colors.heroAccent,
    borderRadius: 32,
    paddingHorizontal: spacing.colossal,
    paddingVertical: spacing.giant,
    minWidth: 160,
  },
  controlBtnFocused: {
    borderColor: colors.focusRing,
    borderWidth: 3,
    backgroundColor: 'rgba(255, 255, 255, 0.35)',
    transform: [{scale: 1.08}],
  },
  playPauseBtnFocused: {
    borderColor: colors.focusRing,
    borderWidth: 3,
    backgroundColor: '#FF1F2D',
    transform: [{scale: 1.08}],
  },
  controlBtnText: {
    color: colors.textPrimary,
    fontSize: fontSizes.heroAction || 18,
    fontWeight: fontWeights.bold,
  },
});
