import {StyleSheet} from 'react-native';
import {colors} from '../theme/colors';
import {fontSizes, fontWeights} from '../theme/fonts';
import {borderRadius, sizes, spacing} from '../theme/sizes';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.shadowDark,
  },
  backdropPoster: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: colors.shadowDark,
    zIndex: 0,
  },
  backdropImageStyle: {
    opacity: 0.5,
  },
  videoSurface: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: colors.transparent,
    zIndex: 1,
  },
  shakaSurfaceContainer: {
    ...StyleSheet.absoluteFillObject,
    alignItems: 'center',
    justifyContent: 'center',
  },
  shakaVideoSurface: {
    backgroundColor: colors.shadowDark,
  },
  overlayContainer: {
    ...StyleSheet.absoluteFillObject,
    justifyContent: 'space-between',
    paddingHorizontal: spacing.huge,
    paddingVertical: spacing.huge,
    zIndex: 10,
  },
  topHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingTop: spacing.lg,
  },
  backButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.chipBackground,
    borderRadius: borderRadius.xl,
    paddingHorizontal: spacing.xxxl,
    paddingVertical: spacing.lg,
    borderWidth: spacing.borderMedium,
    borderColor: colors.borderLight,
    marginRight: spacing.huge,
  },
  backButtonFocused: {
    backgroundColor: colors.heroAccent,
    borderColor: colors.focusRing,
    borderWidth: spacing.borderExtraUltra,
    transform: [{scale: 1.05}],
  },
  backButtonText: {
    color: colors.textPrimary,
    fontSize: fontSizes.heroAction,
    fontWeight: fontWeights.bold,
  },
  titleContainer: {
    flex: 1,
    marginLeft: spacing.lg,
  },
  movieTitle: {
    color: colors.textPrimary,
    fontSize: fontSizes.userName,
    fontWeight: fontWeights.bold,
    textShadowColor: colors.textShadow,
    textShadowOffset: {width: spacing.none, height: spacing.xxs},
    textShadowRadius: spacing.sm,
  },
  movieSub: {
    color: colors.textPrimary,
    opacity: 0.8,
    fontSize: fontSizes.caption,
    marginTop: spacing.xs,
  },
  qualityBadge: {
    backgroundColor: colors.heroAccent,
    paddingHorizontal: spacing.huge,
    paddingVertical: spacing.sm,
    borderRadius: borderRadius.xs,
  },
  qualityBadgeText: {
    color: colors.textPrimary,
    fontWeight: fontWeights.bold,
    fontSize: fontSizes.small,
    letterSpacing: 1,
  },
  seekbarBadge: {
    backgroundColor: 'rgba(0, 173, 225, 0.25)',
    borderColor: '#00ADE1',
    borderWidth: 1.5,
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.sm,
    borderRadius: borderRadius.xs,
    marginLeft: spacing.lg,
  },
  seekbarBadgeText: {
    color: colors.textPrimary,
    fontWeight: fontWeights.bold,
    fontSize: fontSizes.small,
    letterSpacing: 1,
  },
  ccButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.chipBackground,
    borderRadius: borderRadius.xl,
    paddingHorizontal: spacing.xl,
    paddingVertical: spacing.sm,
    borderWidth: spacing.borderMedium,
    borderColor: colors.borderLight,
    marginLeft: spacing.lg,
  },
  ccButtonFocused: {
    backgroundColor: colors.heroAccent,
    borderColor: colors.focusRing,
    borderWidth: spacing.borderExtraUltra,
    transform: [{scale: 1.05}],
    paddingRight: spacing.xl,
  },
  ccButtonActive: {
    borderColor: colors.heroAccent,
    backgroundColor: 'rgba(229, 9, 20, 0.28)',
  },
  ccBadgeText: {
    color: colors.textPrimary,
    fontSize: fontSizes.small,
    fontWeight: fontWeights.extraBold,
    letterSpacing: 1,
    marginRight: spacing.xs,
  },
  ccLabelText: {
    color: colors.textPrimary,
    fontSize: fontSizes.caption,
    fontWeight: fontWeights.bold,
  },
  ccChevronText: {
    color: colors.textPrimary,
    fontSize: fontSizes.caption,
    fontWeight: fontWeights.bold,
    marginLeft: spacing.xs,
    opacity: 0.8,
  },
  topSubtitlesBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.chipBackground,
    borderRadius: borderRadius.xl,
    paddingHorizontal: spacing.xl,
    paddingVertical: spacing.sm,
    borderWidth: spacing.borderMedium,
    borderColor: colors.borderLight,
    marginLeft: spacing.lg,
  },
  topSubtitlesBadgeActive: {
    borderColor: colors.heroAccent,
    backgroundColor: 'rgba(229, 9, 20, 0.28)',
  },
  topSubtitlesBadgeFocused: {
    backgroundColor: colors.heroAccent,
    borderColor: colors.focusRing,
    borderWidth: spacing.borderExtraUltra,
    transform: [{scale: 1.05}],
  },
  topAudioBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.chipBackground,
    borderRadius: borderRadius.xl,
    paddingHorizontal: spacing.xl,
    paddingVertical: spacing.sm,
    borderWidth: spacing.borderMedium,
    borderColor: colors.borderLight,
    marginLeft: spacing.lg,
  },
  topAudioBadgeActive: {
    borderColor: colors.heroAccent,
    backgroundColor: 'rgba(229, 9, 20, 0.28)',
  },
  topAudioBadgeFocused: {
    backgroundColor: colors.heroAccent,
    borderColor: colors.focusRing,
    borderWidth: spacing.borderExtraUltra,
    transform: [{scale: 1.05}],
  },
  audioBadgeText: {
    color: colors.textPrimary,
    fontSize: fontSizes.small,
    fontWeight: fontWeights.extraBold,
    letterSpacing: 1,
    marginRight: spacing.xs,
  },
  audioLabelText: {
    color: colors.textPrimary,
    fontSize: fontSizes.caption,
    fontWeight: fontWeights.bold,
  },
  bottomControls: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing.xl,
    paddingBottom: spacing.xl,
  },
  playerCCButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.chipBackground,
    borderColor: colors.borderLight,
    borderRadius: borderRadius.xl,
    borderWidth: spacing.borderMedium,
    paddingHorizontal: spacing.xxl,
    paddingVertical: spacing.xl,
    gap: spacing.sm,
  },
  playerCCButtonFocused: {
    backgroundColor: colors.heroAccent,
    borderColor: colors.focusRing,
    borderWidth: spacing.borderExtraUltra,
    transform: [{scale: 1.05}],
  },
  playerCCButtonActive: {
    borderColor: colors.heroAccent,
    backgroundColor: 'rgba(229, 9, 20, 0.28)',
  },
  playerCCButtonBadge: {
    backgroundColor: colors.heroAccent,
    color: colors.textPrimary,
    fontSize: fontSizes.cardBadge,
    fontWeight: fontWeights.extraBold,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xxs,
    borderRadius: borderRadius.xs,
    letterSpacing: 1,
    overflow: 'hidden',
  },
  playerCCButtonText: {
    color: colors.textPrimary,
    fontSize: fontSizes.body,
    fontWeight: fontWeights.bold,
  },
  playbackControl: {
    backgroundColor: colors.chipBackground,
    borderColor: colors.borderLight,
    borderRadius: borderRadius.xl,
    borderWidth: spacing.borderMedium,
    minWidth: sizes.playerErrorMaxWidth / 3,
    paddingHorizontal: spacing.colossal,
    paddingVertical: spacing.xl,
    alignItems: 'center',
  },
  playbackControlFocused: {
    backgroundColor: colors.heroAccent,
    borderColor: colors.focusRing,
    borderWidth: spacing.borderExtraUltra,
    transform: [{scale: 1.05}],
  },
  playbackControlText: {
    color: colors.textPrimary,
    fontSize: fontSizes.body,
    fontWeight: fontWeights.bold,
  },
  errorOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: colors.ratingBackground,
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 20,
  },
  errorCard: {
    backgroundColor: colors.cardBackground,
    borderRadius: borderRadius.xl,
    padding: spacing.colossal,
    alignItems: 'center',
    maxWidth: sizes.playerErrorMaxWidth,
    borderWidth: spacing.borderMedium,
    borderColor: colors.borderLight,
  },
  errorTitle: {
    color: colors.heroAccent,
    fontSize: fontSizes.commonHeaderStatus,
    fontWeight: fontWeights.bold,
    marginBottom: spacing.xl,
  },
  errorBody: {
    color: colors.textPrimary,
    fontSize: fontSizes.body,
    textAlign: 'center',
    marginBottom: spacing.huge,
    opacity: 0.9,
  },
  retryButton: {
    backgroundColor: colors.heroAccent,
    borderRadius: borderRadius.sm,
    paddingHorizontal: spacing.giant,
    paddingVertical: spacing.xl,
  },
  retryButtonText: {
    color: colors.textPrimary,
    fontSize: fontSizes.body,
    fontWeight: fontWeights.bold,
  },
});
