export const strings = {
  appName: 'LogiXstream',

  // Navigation & Screen Headers
  nav: {
    homeTitle: 'Discover Movies',
    homeDesc: 'Explore thousands of movies and TV shows.',
    moviesTitle: 'Movies Collection',
    moviesDesc: 'Browse all blockbuster movies.',
    seriesTitle: 'TV Series & Shows',
    seriesDesc: 'Binge-watch top-rated TV series.',
    categoriesTitle: 'Explore Genres',
    categoriesDesc: 'Browse content by categories and genres.',
    searchTitle: 'Search Catalog',
    searchDesc: 'Search by title, genre, cast, or director.',
    settingsTitle: 'Account & Settings',
    settingsDesc: 'Manage your profile, avatar, and viewing preferences.',
    profileTitle: 'Profile',
    profileDesc: 'Review your account details and avatar.',
    editProfileTitle: 'Edit Profile',
    editProfileDesc: 'Update your profile, avatar, and preferences.',
    videoPlayerTitle: 'Now Playing',
    videoPlayerDesc: 'Playing selected video stream.',
    videoSampleTitle: 'LogiXstream Feature Movie',
    videoSampleGenre: 'Action • Sci-Fi',
    videoSampleRating: '⭐ 8.5 / 10',
    moviesHeaderTitle: 'Blockbuster Movies',
    moviesHeaderSubtitle:
      'Browse handpicked hit films, trending titles, and critically acclaimed masterpieces.',
    myListTitle: 'My List',
    myListDesc: 'Browse and watch movies saved to your personal watchlist.',
    myListHeaderTitle: 'My List',
    myListHeaderSubtitle:
      'Browse handpicked movies saved to your active profile watchlist.',
  },

  liveTV: {
    headerTitle: 'LogiXstream • Live TV',
    screenTitle: 'LIVE TV',
    screenSubtitle: 'Browse what is on now and coming up next.',
    loadingSchedule: 'Loading schedule…',
    unavailableProgramme: 'Programme information unavailable.',
    focusProgramme: 'Focus a programme to see its details.',
    loadingChannels: 'Loading live channels…',
    futureProgrammeTitle: 'Programme not available',
    futureProgrammeMessage: 'This programme has not started yet.',
    playbackUnavailableTitle: 'Live stream unavailable',
    playbackUnavailableMessage:
      'This channel does not provide an authorized playback URL.',
    futureProgrammeDismiss: 'OK',
    freeLiveFilter: 'Free Live',
    freeChannelsFilter: 'Free Channels',
    allChannelsFilter: 'All Channels',
    filters: 'Filters',
    noFreeLiveChannels: 'No channels are available for this filter.',
    showAllChannels: 'Show All Channels',
    allCategories: 'All Categories',
    categoryNews: 'News',
    categoryEntertainment: 'Entertainment',
    categorySports: 'Sports',
    categoryMovies: 'Movies',
    categoryKids: 'Kids',
    categoryCulture: 'Culture',
    categoryRegional: 'Regional',
    categoryDocumentary: 'Documentary',
    isLive: '● LIVE',
  },

  // Side Menu Options
  sideMenu: {
    home: 'Home',
    movies: 'Movies',
    liveTV: 'Live TV',
    myList: 'My List',
    series: 'Series',
    categories: 'Categories',
    search: 'Search',
    settings: 'Settings',
  },

  // Common Header Badges
  header: {
    hd: 'HD',
    uhd: '4K ULTRA HD',
    hdr: 'HDR10+',
    atmos: 'DOLBY ATMOS',
    live: 'LIVE',
  },

  // Actions & Buttons
  actions: {
    watchNow: 'Watch Now',
    play: 'Play',
    favourite: '♡ Add to Favourites',
    inFavourites: '♥ Remove from Favourites',
    addToMyList: '+ Add to My List',
    inMyList: '✓ In My List',
    removeFromMyList: '✕ Remove from My List',
    pause: 'Pause',
    addWatchlist: '+ Add to Watchlist',
    watchlist: 'x Remove from Watchlist',
    trailer: 'Trailer',
    signIn: 'Sign In',
    register: 'Create Account',
    logOut: 'Log Out',
    registerNow: "Don't have an account? Register Now",
    alreadyHaveAccount: 'Already have an account? Sign In',
    retry: 'Retry',
    back: 'Back',
    backToDetails: 'Back to Details',
    goBack: 'Go Back',
    removeFavourite: '✕ Remove Favourite',
    removeWatchlist: '✕ Remove Watchlist',
    backChevron: '‹',
  },

  // Toasts
  toasts: {
    signInToAddFavourites: 'Please sign in to add favourites.',
    signInToRemoveFavourites: 'Please sign in to remove favourites.',
    signInToAddToWatchlist: 'Please sign in to add to My List.',
    signInToRemoveFromWatchlist: 'Please sign in to remove from My List.',
    selectProfileToAddToWatchlist: 'Please select a profile to add to My List.',
    addedToWatchlist: 'Added to My List',
    removedFromWatchlist: 'Removed from My List',
  },

  // My List
  myList: {
    title: 'My List',
    screenTitle: 'LogiXstream • My List',
    emptyTitle: 'Your Watchlist is empty',
    emptySubtitle:
      'Explore blockbuster movies and trending titles to add them to your personal watchlist.',
    exploreButton: 'Explore Movies',
    loading: 'Loading your watchlist...',
    errorTitle: 'Unable to load watchlist',
    errorSubtitle: 'Please check your connection and try again.',
    retry: 'Retry',
    itemCount: (count: number) =>
      count === 1 ? '1 Saved Title' : `${count} Saved Titles`,
  },

  // Auth & Settings
  auth: {
    loginTitle: 'Sign In',
    loginSubtitle: 'Sign in to your LogiXstream Account',
    registerTitle: 'Create Account',
    registerSubtitle: 'Register for LogiXstream Streaming Services',
    usernameLabel: 'Username',
    emailLabel: 'Email Address',
    passwordLabel: 'Password',
    subscriptionLabel: 'Subscription Plan',
    cityLabel: 'City',
    countryLabel: 'Country',
    accountUidLabel: 'Account UID',
    subscriptionTierLabel: 'Subscription Tier',
    profileSection: 'Profile',
    preferencesSection: 'User Preferences',
    avatarLabel: 'Avatar',
    themeLabel: 'Theme',
    notificationsLabel: 'Notifications',
    autoplayLabel: 'Autoplay',
    profileSummary: 'Profile Summary',
    accountInformation: 'Account Information',
    accountInformationHint: 'Your membership and location details',
    viewingPreferences: 'Viewing Preferences',
    viewingPreferencesHint: 'Personalize playback and appearance',
    activeMembership: 'Active Membership',
    profileReady: 'Profile Ready',
    chooseAvatar: 'Choose your avatar',
    chooseAvatarHint: 'Use Left and Right to choose a style',
    saveChanges: 'Save Changes',
    cancelChanges: 'Cancel',
    editProfile: 'Edit Profile',
    viewProfile: 'View Profile',
    notificationsHint: 'Receive new release alerts',
    autoplayHint: 'Play the next episode automatically',
    themeHint: 'Interface highlight color',
    preferenceUpdateFailed: 'Unable to update this preference. Try again.',
    notSignedInTitle: 'Not Signed In',
    notSignedInSubtitle:
      'Please sign in or create an account to access premium features.',
    defaultUser: 'LogiXstream User',
    defaultSub: 'Standard',
    avatarInitial: 'initial',
    avatarBadge: 'Avatar',
    notSpecified: 'Not specified',
    notAvailable: 'N/A',
  },

  // Multiple Profiles
  profiles: {
    whosWatching: "Who's Watching?",
    selectProfileSubtitle: 'Choose your profile to start watching',
    addProfile: 'Add Profile',
    addProfileSymbol: '+',
    addNewProfileAccessibility: 'Add New Profile',
    createProfileTitle: 'Add Profile',
    createProfileSubtitle: 'Add a viewing profile for your household',
    createProfileSubmit: 'Create Profile',
    editProfileTitle: 'Edit Profile',
    editProfileSubtitle: 'Update your profile name, avatar, and Kids mode',
    profileNameLabel: 'Profile Name',
    profileNamePlaceholder: 'e.g. Vihaan',
    avatarLabel: 'Choose Avatar',
    avatarOptionAccessibility: (name: string) => `Avatar option ${name}`,
    profileCardAccessibility: (
      name: string,
      isKids: boolean,
      isActive: boolean,
    ) =>
      `Profile ${name}${isKids ? ', Kids Profile' : ''}${
        isActive ? ', Currently Active' : ''
      }`,
    kidsProfileLabel: 'Kids Profile',
    kidsProfileHint:
      'Only show family-friendly movies and shows suitable for all ages',
    kidsProfileShortHint: 'Family-friendly content only',
    switchProfile: 'Switch Profile',
    switchProfileHint: 'Switch to a different viewing profile',
    deleteProfile: 'Delete Profile',
    deleteProfileHint: 'Remove this profile from your account',
    deleteProfileConfirmTitle: 'Delete Profile?',
    deleteProfileConfirmMessage: (name: string) =>
      `Are you sure you want to delete profile "${name}"? This action cannot be undone.`,
    deleteProfileGenericConfirmMessage:
      'Are you sure you want to delete this profile? This action cannot be undone.',
    deleteProfileConfirmButton: 'Delete Profile',
    deleteProfileCancelButton: 'Cancel',
    deleteProfileFailed: 'Failed to delete profile.',
    confirmDeleteAccessibility: 'Confirm delete profile',
    cancelDeleteAccessibility: 'Cancel delete',
    cannotDeleteLastProfile:
      'You cannot delete this profile because every account must have at least one viewing profile.',
    maxProfilesReached: 'Maximum of 5 profiles reached for this account.',
    nameRequired: 'Profile name is required.',
    nameTooLong: 'Profile name must be at most 20 characters.',
    nameInvalidChars: 'Profile name contains invalid characters.',
    enterProfileName: 'Please enter a profile name (1–20 characters).',
    profileCreatedSuccess: 'Profile created successfully.',
    profileUpdatedSuccess: 'Profile updated successfully.',
    profileDeletedSuccess: 'Profile deleted successfully.',
    kidsBadge: 'KIDS',
    kidsProfileType: 'Kids Profile',
    activeBadge: 'ACTIVE',
    manageProfiles: 'Manage Profiles',
    loadingProfiles: 'Loading profiles...',
    errorLoadingProfiles: 'Failed to load profiles. Please try again.',
    noProfilesTitle: 'No Profiles Found',
    noProfilesSubtitle: 'Create your first viewing profile to get started.',
  },

  common: {
    on: 'On',
    off: 'Off',
    locked: 'Locked',
    primaryViewer: 'Primary viewer',
    saving: 'Saving...',
    autoSaved: 'Auto-saved',
    selected: 'Selected',
    select: 'Select',
    playbackAndAlerts: 'Playback and alerts',
    remoteHint: 'Use the remote arrows to move. Press OK to select.',
    accountOverview: 'Account overview',
    avatarAndDetails: 'Avatar and personal details',
    signOutOfThisTV: 'Sign out of this TV',
    yourPublicProfile: 'Your public profile and location',
  },

  // Placeholders
  placeholders: {
    email: 'user@example.com',
    password: 'Enter your password',
    passwordMin: 'Min 6 characters',
    username: 'e.g. user_streamer',
    city: 'e.g. Bangalore',
    country: 'e.g. India',
    search: 'Search movies, series, cast...',
    searchAccessibility: 'Search input field',
  },

  // Subscription Tiers
  subscriptions: {
    free: 'Free',
    basic: 'Basic',
    premium: 'Premium',
    ultra4k: '4K Ultra',
  },

  // Validation & Errors
  errors: {
    enterUsername: 'Please enter a username.',
    validEmail: 'Please enter a valid email address.',
    enterPassword: 'Please enter your password.',
    passwordLength: 'Password must be at least 6 characters.',
    enterCity: 'Please enter your city.',
    enterCountry: 'Please enter your country.',
    invalidLogin: 'Invalid email or password. Please try again.',
    networkUnavailable:
      'No Wi-Fi or network connection detected. Please check your connection and try again.',
    noInternetToast:
      'Wi-Fi is connected, but the internet is not reachable right now.',
    googleBlocked:
      'Internet is available, but Google sign-in cannot be reached from this device. Please check the network or try again later.',
    networkProbeTimeout:
      'The network check timed out. Please try again or check the connection.',
    failedRegister: 'Failed to create account. Please try again.',
    playbackError: 'Playback Error',
    videoPlaybackUnavailable: 'Unable to play video stream.',
  },

  // Movie Detail & Categories
  movieDetail: {
    overview: 'Overview',
    castCrew: 'Cast & Crew',
    moreLikeThis: 'More Like This',
    rating: 'Rating',
    duration: 'Duration',
    releaseYear: 'Release Year',
    genre: 'Genre',
    director: 'Director',
    seasons: 'Seasons',
  },

  hero: {
    continueWatching: 'Continue Watching',
    addToFavourites: 'Add to Favourites',
    removeFromFavourites: 'Remove from Favourites',
    signInToAddFavourites: 'Please sign in to add favourites.',
    original: 'LOGIXSTREAM ORIGINAL',
    newRelease: 'NEW RELEASE',
    uhd: '4K UHD',
    playAccessibility: (title: string) => `Play ${title}`,
    addToListAccessibility: (title: string) => `Add ${title} to Favourites`,
    slideAccessibility: (index: number, total: number, title: string) =>
      `Slide ${index} of ${total}: ${title}`,
  },

  library: {
    favourites: 'Favourites',
  },

  // Search Screen
  search: {
    noResults: 'No results found for',
    trySearchingElse: 'Try searching for something else.',
    moviesShowsGenres: 'Search movies, shows, and genres',
    clearText: 'Clear search text',
    pressOk: 'Press OK',
  },

  // Parental Controls & PIN
  parentalControls: {
    title: 'Parental Controls',
    subtitle:
      'Manage your Parent PIN and content restrictions for Kids profiles.',
    settingsSection: 'Parental Controls',
    settingsHint:
      'Set a PIN to lock profile switching and manage Kids content limits',
    setPin: 'Set Parent PIN',
    changePin: 'Change Parent PIN',
    removePin: 'Remove Parent PIN',
    pinStatusEnabled: 'Enabled (4-digit lock active)',
    pinStatusDisabled: 'Not configured',
    enterPinTitle: 'Enter Parent PIN',
    enterPinSubtitle: 'Please enter your 4-digit Parent PIN to continue.',
    setupPinTitle: 'Set Up Parent PIN',
    setupPinSubtitle: 'Choose a 4-digit numeric PIN for parental controls.',
    confirmPinTitle: 'Confirm Parent PIN',
    confirmPinSubtitle: 'Re-enter your 4-digit PIN to confirm.',
    changePinTitle: 'Change Parent PIN',
    changePinSubtitle: 'Enter your new 4-digit PIN.',
    enterCurrentPinSubtitle: 'Enter your current 4-digit PIN first.',
    pinMismatch: 'PINs do not match. Please try again.',
    incorrectPin: 'Incorrect PIN. Access denied.',
    pinMustBe4Digits: 'PIN must be exactly 4 numeric digits.',
    pinSetSuccess: 'Parent PIN updated successfully.',
    pinRemovedSuccess: 'Parent PIN removed.',
    switchFromKidsLockMessage:
      'Parent PIN is required to switch from a Kids profile to an adult profile.',
    profileManagementLockMessage:
      'Parent PIN is required to manage profiles and change maturity settings.',
    contentRestrictedTitle: 'Content Restricted',
    contentRestrictedMessage:
      'This content is not available for the current profile.',
    contentRestrictedSubtitle:
      'Content maturity rating exceeds this profile limit or is unclassified.',
    maturityLimitLabel: 'Allowed Content Limit',
    maturityLimitHint: 'Highest maturity rating allowed for this Kids profile',
    backToHome: 'Back to Home',
    switchProfileButton: 'Switch Profile',
    clearPinDigit: 'Clear',
    submitPin: 'Submit',
    cancel: 'Cancel',
  },

  subtitles: {
    buttonLabel: 'Subtitles',
    ccBadge: 'CC',
    subtitlesTitle: 'Subtitles & Audio',
    selectLanguage: 'Select Subtitles',
    selectLanguageDesc:
      'Choose your preferred subtitle language or turn subtitles off.',
    off: 'Off',
    english: 'English',
    englishCC: 'English [CC]',
    spanish: 'Spanish',
    telugu: 'Telugu',
    hindi: 'Hindi',
    french: 'French',
    german: 'German',
    close: 'Close',
    activeTrack: 'Active',
    subtitlesDisabled: 'Subtitles: Off',
    subtitleActive: (label: string) => `Subtitles: ${label}`,
    tracksAvailable: (count: number) => `${count} Subtitle Languages Available`,
  },

  audioTracks: {
    buttonLabel: 'Audio',
    audioBadge: 'AUDIO',
    audioTracksTitle: 'Audio Languages',
    selectAudioTrack: 'Select Audio Track',
    selectAudioTrackDesc:
      'Choose your preferred audio language and sound format.',
    original: 'Original',
    activeTrack: 'Active',
    close: 'Close',
    audioActive: (label: string) => `Audio: ${label}`,
    tracksAvailable: (count: number) => `${count} Audio Tracks Available`,
    stereo: 'Stereo 2.0',
    surround51: '5.1 Surround',
    dolbyAtmos: 'Dolby Atmos',
  },

  accessibility: {
    retryVideoPlayback: 'Retry video playback',
    backToHome: 'Back to Home',
    subtitlesButton: (label: string) =>
      `Subtitles and closed captions. Currently ${label}`,
    selectSubtitleTrack: (label: string, isSelected: boolean) =>
      `${label} subtitle track${isSelected ? ', currently selected' : ''}`,
    closeSubtitlesModal: 'Close subtitles selection modal',
    audioTracksButton: (label: string) =>
      `Audio track selection. Currently ${label}`,
    selectAudioTrack: (label: string, isSelected: boolean) =>
      `${label} audio track${isSelected ? ', currently selected' : ''}`,
    closeAudioTracksModal: 'Close audio tracks selection modal',
    skipIntroButton: 'Skip intro, forward a few seconds',
    startFromBeginningButton: 'Start video playback from the beginning',
  },

  // Player controls
  playerControls: {
    removeMarker: '- Remove Marker',
    addMarker: '+ Add Marker',
    removeSegment: '- Remove Segment',
    addSegment: '+ Add Segment',
    removeBreakMarker: '- Remove Break Marker',
    addBreakMarker: '+ Add Break Marker',
    removeBreakSegment: '- Remove Break Segment',
    addBreakSegment: '+ Add Break Segment',
    removeMarkerSegment: '- Remove Marker Segment',
    markers: '● Markers',
    limits: '⇥ Limits ⇤',
    pauseAction: '▶',
    playAction: '❚❚',
    breakSegments: '❖ Breaks & Segments',
    longPress: '⏩ Long Press',
    fastForwardRewind: '⏪ FF / REW ⏩',
    rewindButton: '⏪ -10s',
    fastForwardButton: '+10s ⏩',
    skipIntro: 'Skip Intro',
    startFromBeginning: 'Start from Beginning',
    startFromBegining: 'Start from Beginning',
    longPressBadge: 'Long Press: Speed Acceleration (1x, 2x, 3x, 4x, 5x)',
    fastForwardRewindBadge: 'Skip Acceleration (1x, 2x, 3x...)',
    thumbnails: '🖼 Thumbnails',
    thumbnailBadge: 'Thumbnail Images: Video Preview During Seeking',
    thumbnailPreview: 'Preview',
  },
} as const;
