export const fontWeights = {
  semibold: '600',
  bold: 'bold',
} as const;

export const fontSizes = {
  portraitBadge: 10,
  rating: 11,
  genre: 12,
  cardBadge: 13,
  caption: 14,
  body: 16,
  cardTitle: 20,
  commonHeaderStatus: 22,
  heroMeta: 22,
  navArrow: 22,
  castLabel: 22,
  heroEyebrow: 24,
  heroAction: 24,
  subheading: 24,
  synopsis: 28,
  rowTitle: 32,
  sideMenuOption: 34,
  heroDescription: 38,
  moviesTitle: 44,
  sideMenuTitle: 46,
  headerSubtitle: 50,
  tileLabel: 52,
  commonHeaderTitle: 58,
  focusedDescription: 60,
  movieDetailTitle: 72,
  heroTitle: 104,
  screenTitle: 120,
  focusedTitle: 130,
  headerTitle: 150,
} as const;

export const lineHeights = {
  headerTitle: 170,
  focusedTitle: 160,
  focusedDescription: 80,
  tileLabel: 52,
  screenTitle: 144,
  commonHeaderTitle: 68,
  movieDetailTitle: 82,
  heroTitle: 116,
  heroDescription: 52,
} as const;
