// React Native 0.83 on Vega uses Density-Independent Pixels (dp).
// Canvas reference size is 960x540 dp (scale factor 2 on 1080p).
// Font sizes and line heights are scaled for logical dp coordinates.

export const fontWeights = {
  light: '300',
  regular: '400',
  medium: '500',
  semibold: '600',
  bold: 'bold',
  boldWeight: '700',
  extraBold: '800',
  black: '900',
} as const;

export const fontSizes = {
  portraitBadge: 6,
  rating: 6,
  genre: 8,
  small: 9,
  cardBadge: 4,
  caption: 10,
  error: 10,
  body: 11,
  bodySmall: 10,
  label: 11,
  input: 11,
  button: 12,
  cardTitle: 12,
  commonHeaderStatus: 10,
  heroMeta: 10,
  navArrow: 12,
  castLabel: 12,
  heroEyebrow: 13,
  heroAction: 11,
  subheading: 14,
  userName: 14,
  synopsis: 14,
  rowTitle: 16,
  monogram: 17,
  sideMenuOption: 17,
  avatar: 18,
  heroDescription: 19,
  pageTitle: 20,
  moviesTitle: 22,
  sideMenuTitle: 23,
  addIcon: 24,
  headerSubtitle: 25,
  tileLabel: 26,
  commonHeaderTitle: 25,
  focusedDescription: 30,
  movieDetailTitle: 36,
  heroTitle: 52,
  screenTitle: 60,
  focusedTitle: 65,
  headerTitle: 75,
} as const;

export const lineHeights = {
  headerTitle: 85,
  focusedTitle: 80,
  focusedDescription: 40,
  tileLabel: 26,
  screenTitle: 72,
  commonHeaderTitle: 34,
  movieDetailTitle: 41,
  heroTitle: 58,
  heroDescription: 26,
  addIcon: 26,
  dialogBody: 16,
} as const;
