import {StyleSheet} from 'react-native';
import {colors} from '../../theme/colors';
import {fontSizes, fontWeights, lineHeights} from '../../theme/fonts';
import {borderRadius, spacing} from '../../theme/sizes';

export const styles = StyleSheet.create({
  overlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: colors.overlayDark,
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 1000,
  },
  modalCard: {
    width: 1160,
    maxHeight: 820,
    backgroundColor: colors.dialogBackground,
    borderRadius: borderRadius.dialog,
    borderWidth: spacing.borderThick,
    borderColor: colors.cardBorder,
    padding: spacing.xl,
    shadowColor: colors.shadowDark,
    shadowOffset: {width: 0, height: spacing.lg},
    shadowOpacity: 0.8,
    shadowRadius: spacing.xlarge,
  },
  actionRowGuide: {
    width: '100%',
  },
  episodesListGuide: {
    width: '100%',
  },
  headerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: spacing.md,
  },
  badge: {
    backgroundColor: colors.heroAccent,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.xs,
    borderRadius: borderRadius.sm,
    marginRight: spacing.md,
  },
  badgeText: {
    color: colors.textPrimary,
    fontSize: fontSizes.cardBadge,
    fontWeight: fontWeights.extraBold,
    letterSpacing: 1.5,
  },
  seriesTitle: {
    color: colors.textSecondary,
    fontSize: fontSizes.caption,
    fontWeight: fontWeights.semibold,
    letterSpacing: 0.5,
  },
  seasonEpisodeText: {
    color: colors.gold,
    fontSize: fontSizes.caption,
    fontWeight: fontWeights.bold,
    marginLeft: spacing.sm,
  },
  title: {
    color: colors.textPrimary,
    fontSize: fontSizes.subheading,
    fontWeight: fontWeights.extraBold,
    marginBottom: spacing.md,
  },
  contentRow: {
    flexDirection: 'row',
    marginBottom: spacing.lg,
  },
  thumbnail: {
    width: 220,
    height: 124,
    borderRadius: borderRadius.md,
    backgroundColor: colors.cardBackground,
    marginRight: spacing.lg,
  },
  thumbnailPlaceholder: {
    width: 220,
    height: 124,
    borderRadius: borderRadius.md,
    backgroundColor: colors.cardBackground,
    marginRight: spacing.lg,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: colors.cardBorder,
  },
  thumbnailPlaceholderText: {
    color: colors.textSecondary,
    fontSize: fontSizes.button,
    fontWeight: fontWeights.bold,
  },
  detailsColumn: {
    flex: 1,
    justifyContent: 'space-between',
  },
  description: {
    color: colors.textSecondary,
    fontSize: fontSizes.caption,
    lineHeight: lineHeights.dialogBody,
    marginBottom: spacing.sm,
  },
  metaRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.sm,
    marginTop: spacing.xs,
  },
  metaPill: {
    backgroundColor: colors.chipBackground,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xxs,
    borderRadius: borderRadius.xs,
  },
  metaPillText: {
    color: colors.textPrimary,
    fontSize: fontSizes.cardBadge,
    fontWeight: fontWeights.semibold,
  },
  countdownSection: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(229, 9, 20, 0.12)',
    borderWidth: 1,
    borderColor: 'rgba(229, 9, 20, 0.3)',
    borderRadius: borderRadius.md,
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.sm,
    marginBottom: spacing.xl,
  },
  countdownIconBadge: {
    width: 36,
    height: 36,
    borderRadius: borderRadius.circle,
    backgroundColor: colors.heroAccent,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: spacing.md,
  },
  countdownNumber: {
    color: colors.textPrimary,
    fontSize: fontSizes.button,
    fontWeight: fontWeights.extraBold,
  },
  countdownTextContainer: {
    flex: 1,
  },
  countdownText: {
    color: colors.textPrimary,
    fontSize: fontSizes.body,
    fontWeight: fontWeights.bold,
  },
  countdownSubtext: {
    color: colors.textSecondary,
    fontSize: fontSizes.cardBadge,
    marginTop: spacing.xxs,
  },
  disabledAutoplaySection: {
    backgroundColor: colors.cardBackgroundSubtle,
    borderColor: colors.cardBorder,
  },
  disabledAutoplayText: {
    color: colors.textSecondary,
    fontSize: fontSizes.caption,
  },
  actionRow: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    gap: spacing.lg,
  },
  playButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.heroAccent,
    paddingHorizontal: spacing.xxl,
    paddingVertical: spacing.md,
    borderRadius: borderRadius.lg,
    borderWidth: spacing.borderMedium,
    borderColor: colors.transparent,
  },
  playButtonFocused: {
    backgroundColor: colors.heroAccent,
    borderColor: colors.focusRing,
    borderWidth: spacing.borderExtraUltra,
    transform: [{scale: 1.05}],
  },
  playButtonText: {
    color: colors.textPrimary,
    fontSize: fontSizes.button,
    fontWeight: fontWeights.bold,
    letterSpacing: 0.5,
  },
  cancelButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.chipBackground,
    paddingHorizontal: spacing.xxl,
    paddingVertical: spacing.md,
    borderRadius: borderRadius.lg,
    borderWidth: spacing.borderMedium,
    borderColor: colors.cardBorder,
  },
  cancelButtonFocused: {
    backgroundColor: colors.controlFocusedBackground,
    borderColor: colors.focusRing,
    borderWidth: spacing.borderExtraUltra,
    transform: [{scale: 1.05}],
  },
  cancelButtonText: {
    color: colors.textPrimary,
    fontSize: fontSizes.button,
    fontWeight: fontWeights.bold,
  },

  // --- Next Episodes List View Styles ---
  episodesSection: {
    marginTop: spacing.md,
    paddingTop: spacing.sm,
    borderTopWidth: 1,
    borderTopColor: colors.cardBorder,
  },
  episodesHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: spacing.sm,
  },
  episodesHeaderLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
  },
  episodesSectionTitle: {
    color: colors.textPrimary,
    fontSize: fontSizes.body,
    fontWeight: fontWeights.bold,
    letterSpacing: 0.5,
  },
  episodesCountBadge: {
    backgroundColor: colors.chipBackground,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xxs,
    borderRadius: borderRadius.xs,
  },
  episodesCountText: {
    color: colors.textSecondary,
    fontSize: fontSizes.cardBadge,
    fontWeight: fontWeights.semibold,
  },
  tabsContainer: {
    flexDirection: 'row',
    gap: spacing.sm,
  },
  tabButton: {
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.xs,
    borderRadius: borderRadius.sm,
    backgroundColor: colors.cardBackgroundSubtle,
    borderWidth: 1,
    borderColor: colors.cardBorder,
  },
  tabButtonActive: {
    backgroundColor: colors.heroAccent,
    borderColor: colors.heroAccent,
  },
  tabButtonFocused: {
    borderColor: colors.focusRing,
    borderWidth: spacing.borderHeavy,
    backgroundColor: colors.controlFocusedBackground,
    transform: [{scale: 1.05}],
  },
  tabButtonText: {
    color: colors.textSecondary,
    fontSize: fontSizes.caption,
    fontWeight: fontWeights.semibold,
  },
  tabButtonTextActive: {
    color: colors.textPrimary,
    fontWeight: fontWeights.bold,
  },
  episodesListContainer: {
    flexGrow: 0,
  },
  episodesListContent: {
    flexDirection: 'row',
    gap: spacing.md,
    paddingVertical: spacing.sm,
    paddingHorizontal: spacing.xs,
  },
  episodeCard: {
    width: 240,
    backgroundColor: colors.cardBackgroundSubtle,
    borderRadius: borderRadius.md,
    borderWidth: spacing.borderThick,
    borderColor: colors.cardBorder,
    padding: spacing.xs,
    overflow: 'hidden',
  },
  episodeCardFocused: {
    borderColor: colors.focusRing,
    borderWidth: spacing.borderUltra,
    backgroundColor: colors.controlFocusedBackground,
    transform: [{scale: 1.05}],
    shadowColor: colors.shadowDark,
    shadowOffset: {width: 0, height: 4},
    shadowOpacity: 0.9,
    shadowRadius: 8,
    zIndex: 10,
  },
  episodeCardActiveUpNext: {
    borderColor: 'rgba(229, 9, 20, 0.7)',
  },
  episodeCardThumbnailContainer: {
    width: '100%',
    height: 104,
    borderRadius: borderRadius.sm,
    overflow: 'hidden',
    position: 'relative',
    backgroundColor: colors.cardBackground,
  },
  episodeCardThumbnail: {
    width: '100%',
    height: '100%',
  },
  episodeCardPlaceholder: {
    width: '100%',
    height: '100%',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: colors.chipBackground,
  },
  episodeCardPlaceholderText: {
    color: colors.textSecondary,
    fontSize: fontSizes.caption,
    fontWeight: fontWeights.bold,
  },
  episodeCardBadgeTopLeft: {
    position: 'absolute',
    top: spacing.xs,
    left: spacing.xs,
    backgroundColor: 'rgba(0, 0, 0, 0.75)',
    paddingHorizontal: spacing.xs,
    paddingVertical: spacing.xxs,
    borderRadius: borderRadius.xs,
  },
  episodeCardBadgeTopLeftText: {
    color: colors.textPrimary,
    fontSize: 10,
    fontWeight: fontWeights.bold,
  },
  episodeCardBadgeTopRight: {
    position: 'absolute',
    top: spacing.xs,
    right: spacing.xs,
    backgroundColor: colors.heroAccent,
    paddingHorizontal: spacing.xs,
    paddingVertical: spacing.xxs,
    borderRadius: borderRadius.xs,
  },
  episodeCardBadgeTopRightText: {
    color: colors.textPrimary,
    fontSize: 10,
    fontWeight: fontWeights.extraBold,
    letterSpacing: 0.5,
  },
  episodeCardBadgeWatched: {
    position: 'absolute',
    top: spacing.xs,
    right: spacing.xs,
    backgroundColor: colors.chipBackground,
    paddingHorizontal: spacing.xs,
    paddingVertical: spacing.xxs,
    borderRadius: borderRadius.xs,
  },
  episodeCardBadgeWatchedText: {
    color: colors.textSecondary,
    fontSize: 10,
    fontWeight: fontWeights.bold,
  },
  episodeCardDurationBadge: {
    position: 'absolute',
    bottom: spacing.xs,
    right: spacing.xs,
    backgroundColor: 'rgba(0, 0, 0, 0.8)',
    paddingHorizontal: spacing.xs,
    paddingVertical: 1,
    borderRadius: borderRadius.xs,
  },
  episodeCardDurationText: {
    color: colors.textPrimary,
    fontSize: 10,
    fontWeight: fontWeights.semibold,
  },
  episodeCardPlayOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(0, 0, 0, 0.4)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  episodeCardPlayIcon: {
    color: colors.textPrimary,
    fontSize: 26,
    fontWeight: fontWeights.bold,
  },
  episodeCardInfo: {
    paddingHorizontal: spacing.xxs,
    paddingTop: spacing.xs,
  },
  episodeCardTitle: {
    color: colors.textPrimary,
    fontSize: fontSizes.caption,
    fontWeight: fontWeights.bold,
    marginBottom: spacing.xxs,
  },
  episodeCardTitleFocused: {
    color: colors.gold,
  },
  episodeCardMetaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xs,
    marginTop: spacing.xxs,
  },
  episodeCardRating: {
    color: colors.gold,
    fontSize: 11,
    fontWeight: fontWeights.semibold,
  },
  episodeCardMaturityPill: {
    backgroundColor: colors.chipBackground,
    paddingHorizontal: 4,
    paddingVertical: 1,
    borderRadius: 2,
  },
  episodeCardMaturityText: {
    color: colors.textSecondary,
    fontSize: 9,
    fontWeight: fontWeights.semibold,
  },
  episodeCardProgressBar: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    height: 3,
    backgroundColor: 'rgba(255, 255, 255, 0.3)',
  },
  episodeCardProgressBarFill: {
    height: '100%',
    backgroundColor: colors.heroAccent,
  },
  episodeCardFocusedActionHint: {
    color: colors.focusRing,
    fontSize: 10,
    fontWeight: fontWeights.bold,
    marginTop: spacing.xxs,
  },
  emptyEpisodesText: {
    color: colors.textSecondary,
    fontSize: fontSizes.caption,
    fontStyle: 'italic',
    paddingVertical: spacing.md,
  },
});
