import {StyleSheet} from 'react-native';
import {colors} from '../../theme/colors';
import {fontSizes, fontWeights, lineHeights} from '../../theme/fonts';
import {borderRadius, spacing} from '../../theme/sizes';

export const styles = StyleSheet.create({
  overlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: colors.overlayDark,
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 1000,
  },
  modalCard: {
    width: 720,
    maxHeight: 640,
    backgroundColor: colors.dialogBackground,
    borderRadius: borderRadius.dialog,
    borderWidth: spacing.borderThick,
    borderColor: colors.cardBorder,
    padding: spacing.xxl,
    shadowColor: colors.shadowDark,
    shadowOffset: {width: 0, height: spacing.lg},
    shadowOpacity: 0.8,
    shadowRadius: spacing.xlarge,
  },
  headerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: spacing.md,
  },
  badge: {
    backgroundColor: colors.heroAccent,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.xs,
    borderRadius: borderRadius.sm,
    marginRight: spacing.md,
  },
  badgeText: {
    color: colors.textPrimary,
    fontSize: fontSizes.cardBadge,
    fontWeight: fontWeights.extraBold,
    letterSpacing: 1.5,
  },
  seriesTitle: {
    color: colors.textSecondary,
    fontSize: fontSizes.caption,
    fontWeight: fontWeights.semibold,
    letterSpacing: 0.5,
  },
  seasonEpisodeText: {
    color: colors.gold,
    fontSize: fontSizes.caption,
    fontWeight: fontWeights.bold,
    marginLeft: spacing.sm,
  },
  title: {
    color: colors.textPrimary,
    fontSize: fontSizes.subheading,
    fontWeight: fontWeights.extraBold,
    marginBottom: spacing.md,
  },
  contentRow: {
    flexDirection: 'row',
    marginBottom: spacing.lg,
  },
  thumbnail: {
    width: 220,
    height: 124,
    borderRadius: borderRadius.md,
    backgroundColor: colors.cardBackground,
    marginRight: spacing.lg,
  },
  thumbnailPlaceholder: {
    width: 220,
    height: 124,
    borderRadius: borderRadius.md,
    backgroundColor: colors.cardBackground,
    marginRight: spacing.lg,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: colors.cardBorder,
  },
  thumbnailPlaceholderText: {
    color: colors.textSecondary,
    fontSize: fontSizes.button,
    fontWeight: fontWeights.bold,
  },
  detailsColumn: {
    flex: 1,
    justifyContent: 'space-between',
  },
  description: {
    color: colors.textSecondary,
    fontSize: fontSizes.caption,
    lineHeight: lineHeights.dialogBody,
    marginBottom: spacing.sm,
  },
  metaRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.sm,
    marginTop: spacing.xs,
  },
  metaPill: {
    backgroundColor: colors.chipBackground,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xxs,
    borderRadius: borderRadius.xs,
  },
  metaPillText: {
    color: colors.textPrimary,
    fontSize: fontSizes.cardBadge,
    fontWeight: fontWeights.semibold,
  },
  countdownSection: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(229, 9, 20, 0.12)',
    borderWidth: 1,
    borderColor: 'rgba(229, 9, 20, 0.3)',
    borderRadius: borderRadius.md,
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.sm,
    marginBottom: spacing.xl,
  },
  countdownIconBadge: {
    width: 36,
    height: 36,
    borderRadius: borderRadius.circle,
    backgroundColor: colors.heroAccent,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: spacing.md,
  },
  countdownNumber: {
    color: colors.textPrimary,
    fontSize: fontSizes.button,
    fontWeight: fontWeights.extraBold,
  },
  countdownTextContainer: {
    flex: 1,
  },
  countdownText: {
    color: colors.textPrimary,
    fontSize: fontSizes.body,
    fontWeight: fontWeights.bold,
  },
  countdownSubtext: {
    color: colors.textSecondary,
    fontSize: fontSizes.cardBadge,
    marginTop: spacing.xxs,
  },
  disabledAutoplaySection: {
    backgroundColor: colors.cardBackgroundSubtle,
    borderColor: colors.cardBorder,
  },
  disabledAutoplayText: {
    color: colors.textSecondary,
    fontSize: fontSizes.caption,
  },
  actionRow: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    gap: spacing.lg,
  },
  playButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.heroAccent,
    paddingHorizontal: spacing.xxl,
    paddingVertical: spacing.md,
    borderRadius: borderRadius.lg,
    borderWidth: spacing.borderMedium,
    borderColor: colors.transparent,
  },
  playButtonFocused: {
    backgroundColor: colors.heroAccent,
    borderColor: colors.focusRing,
    borderWidth: spacing.borderExtraUltra,
    transform: [{scale: 1.05}],
  },
  playButtonText: {
    color: colors.textPrimary,
    fontSize: fontSizes.button,
    fontWeight: fontWeights.bold,
    letterSpacing: 0.5,
  },
  cancelButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.chipBackground,
    paddingHorizontal: spacing.xxl,
    paddingVertical: spacing.md,
    borderRadius: borderRadius.lg,
    borderWidth: spacing.borderMedium,
    borderColor: colors.cardBorder,
  },
  cancelButtonFocused: {
    backgroundColor: colors.controlFocusedBackground,
    borderColor: colors.focusRing,
    borderWidth: spacing.borderExtraUltra,
    transform: [{scale: 1.05}],
  },
  cancelButtonText: {
    color: colors.textPrimary,
    fontSize: fontSizes.button,
    fontWeight: fontWeights.bold,
  },
});
