import {StyleSheet} from 'react-native';
import {colors} from '../../theme/colors';
import {fontSizes, fontWeights, lineHeights} from '../../theme/fonts';
import {borderRadius, sizes, spacing} from '../../theme/sizes';

export const styles = StyleSheet.create({
  overlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: colors.overlayDark,
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 1100,
  },
  dialog: {
    width: 580,
    backgroundColor: colors.dialogBackground,
    borderRadius: borderRadius.dialog,
    borderWidth: spacing.borderThick,
    borderColor: colors.chipBackground,
    padding: spacing.xxl,
    alignItems: 'center',
    shadowColor: colors.shadowDark,
    shadowOffset: {width: 0, height: spacing.lg},
    shadowOpacity: 0.7,
    shadowRadius: spacing.xlarge,
    elevation: spacing.xlarge,
  },
  lockIconCircle: {
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: colors.cardBorder,
    borderWidth: spacing.borderThick,
    borderColor: colors.heroAccent,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: spacing.lg,
  },
  lockIconText: {
    fontSize: 28,
  },
  title: {
    color: colors.textPrimary,
    fontSize: fontSizes.subheading,
    fontWeight: fontWeights.extraBold,
    marginBottom: spacing.xs,
    textAlign: 'center',
  },
  subtitle: {
    color: colors.textSecondary,
    fontSize: fontSizes.caption,
    lineHeight: lineHeights.dialogBody,
    textAlign: 'center',
    marginBottom: spacing.lg,
    paddingHorizontal: spacing.md,
  },
  stepIndicator: {
    color: colors.heroAccent,
    fontSize: fontSizes.cardBadge,
    fontWeight: fontWeights.boldWeight,
    textTransform: 'uppercase',
    letterSpacing: 1.5,
    marginBottom: spacing.sm,
  },
  dotsRow: {
    flexDirection: 'row',
    gap: spacing.lg,
    marginBottom: spacing.lg,
    justifyContent: 'center',
    alignItems: 'center',
  },
  dot: {
    width: 22,
    height: 22,
    borderRadius: 11,
    borderWidth: 2,
    borderColor: colors.cardBorder,
    backgroundColor: colors.transparent,
  },
  dotFilled: {
    backgroundColor: colors.heroAccent,
    borderColor: colors.heroAccent,
    transform: [{scale: 1.15}],
  },
  errorBanner: {
    backgroundColor: colors.errorBackground,
    borderRadius: borderRadius.md,
    borderWidth: 1,
    borderColor: colors.errorBorder,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.xs,
    marginBottom: spacing.md,
    width: '100%',
  },
  errorText: {
    color: colors.errorText,
    fontSize: fontSizes.cardBadge,
    fontWeight: fontWeights.semibold,
    textAlign: 'center',
  },
  keypadContainer: {
    width: 320,
    marginBottom: spacing.md,
  },
  keypadRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: spacing.sm,
  },
  keyButton: {
    width: 90,
    height: 52,
    borderRadius: borderRadius.lg,
    backgroundColor: colors.cardBorder,
    borderWidth: 2,
    borderColor: colors.transparent,
    alignItems: 'center',
    justifyContent: 'center',
  },
  keyButtonFocused: {
    borderColor: colors.textPrimary,
    backgroundColor: colors.controlBackground,
    transform: [{scale: 1.06}],
  },
  keyButtonText: {
    color: colors.textPrimary,
    fontSize: fontSizes.body,
    fontWeight: fontWeights.boldWeight,
  },
  keyButtonUtility: {
    backgroundColor: colors.cardBackground,
  },
  keyButtonUtilityText: {
    color: colors.textSecondary,
    fontSize: fontSizes.caption,
    fontWeight: fontWeights.semibold,
  },
  footerActions: {
    flexDirection: 'row',
    width: '100%',
    justifyContent: 'center',
    gap: spacing.lg,
  },
  cancelButton: {
    height: sizes.dialogButtonHeight,
    paddingHorizontal: spacing.xlarge,
    borderRadius: borderRadius.xl,
    backgroundColor: colors.cardBorder,
    borderWidth: spacing.borderThick,
    borderColor: colors.transparent,
    alignItems: 'center',
    justifyContent: 'center',
  },
  cancelButtonFocused: {
    borderColor: colors.textPrimary,
    backgroundColor: colors.controlBackground,
    transform: [{scale: 1.04}],
  },
  cancelButtonText: {
    color: colors.textPrimary,
    fontSize: fontSizes.caption,
    fontWeight: fontWeights.boldWeight,
  },
});
