import {StyleSheet, ViewStyle} from 'react-native';
import {SEEKBAR_COLORS} from '../../constants/seekbarColors';
import {colors} from '../../theme/colors';

const TICK_SIZE = 4;
const THUMB_SIZE = 16;
const SEEKBAR_HEIGHT = 4;

export const circleStyle = (diameter: number): ViewStyle => ({
  width: diameter,
  height: diameter,
  borderRadius: diameter / 2,
});

export const styles = StyleSheet.create({
  container: {
    width: '100%',
    paddingHorizontal: 12,
    paddingVertical: 6,
    backgroundColor: colors.seekBarBackground,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: colors.cardBorder,
    shadowColor: SEEKBAR_COLORS.SHADOW_BLACK,
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.5,
    shadowRadius: 5,
  },
  topControlsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 6,
    flexWrap: 'wrap',
    gap: 6,
  },
  leftControls: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  playPauseButton: {
    width: 26,
    height: 26,
    borderRadius: 13,
    backgroundColor: colors.chipBackground,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1.5,
    borderColor: colors.controlFocusedBackground,
  },
  playPauseButtonFocused: {
    backgroundColor: SEEKBAR_COLORS.PRIMARY_BLUE,
    borderColor: SEEKBAR_COLORS.WHITE,
    transform: [{scale: 1.08}],
  },
  playPauseIconText: {
    color: SEEKBAR_COLORS.WHITE,
    fontSize: 11,
    fontWeight: 'bold',
    textAlign: 'center',
  },
  timeText: {
    color: SEEKBAR_COLORS.WHITE,
    fontSize: 10,
    fontWeight: '600',
    letterSpacing: 0.3,
    marginLeft: 8,
  },
  centerExtraControls: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
  },
  typeSelectorRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  typeSelectorLabel: {
    color: SEEKBAR_COLORS.MEDIUM_GREY,
    fontSize: 8.5,
    fontWeight: '700',
    letterSpacing: 0.5,
    textTransform: 'uppercase',
    marginRight: 2,
  },
  typePill: {
    paddingHorizontal: 6,
    paddingVertical: 3,
    borderRadius: 7,
    backgroundColor: colors.buttonSecondaryBackground,
    borderWidth: 1,
    borderColor: colors.controlBackground,
  },
  typePillActive: {
    backgroundColor: colors.seekBarTypePil,
    borderColor: SEEKBAR_COLORS.PRIMARY_BLUE,
  },
  typePillFocused: {
    backgroundColor: SEEKBAR_COLORS.PRIMARY_BLUE,
    borderColor: SEEKBAR_COLORS.WHITE,
    transform: [{scale: 1.05}],
  },
  typePillText: {
    color: SEEKBAR_COLORS.WHITE,
    fontSize: 8.5,
    fontWeight: '700',
    letterSpacing: 0.3,
  },
  typePillTextActive: {
    color: SEEKBAR_COLORS.WHITE,
  },
  actionButton: {
    backgroundColor: colors.seekBarActionButton,
    borderColor: SEEKBAR_COLORS.PRIMARY_BLUE,
    borderWidth: 1,
    paddingHorizontal: 7,
    paddingVertical: 3,
    borderRadius: 7,
  },
  actionButtonFocused: {
    backgroundColor: SEEKBAR_COLORS.PRIMARY_BLUE,
    borderColor: SEEKBAR_COLORS.WHITE,
    transform: [{scale: 1.05}],
  },
  actionButtonText: {
    color: SEEKBAR_COLORS.WHITE,
    fontSize: 9,
    fontWeight: '700',
  },
  limitsBadge: {
    backgroundColor: colors.seekBarLimitsBadge,
    borderColor: SEEKBAR_COLORS.YELLOW,
    borderWidth: 1,
    paddingHorizontal: 6,
    paddingVertical: 2.5,
    borderRadius: 6,
  },
  limitsBadgeText: {
    color: SEEKBAR_COLORS.YELLOW,
    fontSize: 8.5,
    fontWeight: '700',
    letterSpacing: 0.3,
  },
  seekbarWrapper: {
    width: '100%',
    paddingVertical: 4,
    minHeight: 26,
    justifyContent: 'center',
  },
  focusedThumb: {
    borderRadius: 8,
    height: THUMB_SIZE,
    width: THUMB_SIZE,
    backgroundColor: SEEKBAR_COLORS.PRIMARY_BLUE,
  },
  unfocusedThumb: {
    borderRadius: 8,
    height: THUMB_SIZE,
    width: 5,
    backgroundColor: SEEKBAR_COLORS.PRIMARY_BLUE,
  },
  markersBar: {
    height: SEEKBAR_HEIGHT,
  },
  seekbarTrackTimeshiftPart: {
    backgroundColor: 'transparent',
  },
  savedDelayArrow: {
    width: 10,
    height: 10,
    left: '-50%',
    top: (SEEKBAR_HEIGHT + THUMB_SIZE) / 2 - 2,
  },
  tickStyle: {
    position: 'relative',
    top: (SEEKBAR_HEIGHT - TICK_SIZE) / 2,
    left: '-50%',
    backgroundColor: SEEKBAR_COLORS.WHITE,
  },
  belowMarker: {
    height: 18,
    width: 32,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'transparent',
  },
  belowMarkerText: {
    color: SEEKBAR_COLORS.WHITE,
    fontSize: 8,
    fontWeight: 'bold',
    marginTop: 9,
    backgroundColor: colors.seekBarBelowMarkerText,
    paddingHorizontal: 4,
    paddingVertical: 1,
    borderRadius: 2,
    overflow: 'hidden',
  },
  limitMarker: {
    height: 14,
    width: 3,
    borderRadius: 1.5,
    backgroundColor: SEEKBAR_COLORS.WHITE,
    position: 'relative',
    top: -5,
    left: '-50%',
  },
  fastForwardRewindImage: {
    height: 13,
    width: 13,
  },
  fastForwardRewindLabel: {
    fontSize: 11,
    fontWeight: '700',
    lineHeight: 14,
    letterSpacing: 0.5,
    color: SEEKBAR_COLORS.WHITE,
    marginHorizontal: 2,
  },
  aboveThumb: {
    alignItems: 'center',
    justifyContent: 'center',
    height: 38,
    width: 60,
    display: 'flex',
    flexDirection: 'row',
  },
  longPressBadge: {
    backgroundColor: colors.seekBarLimitsBadge,
    borderColor: SEEKBAR_COLORS.PRIMARY_BLUE,
    borderWidth: 1,
    paddingHorizontal: 6,
    paddingVertical: 2.5,
    borderRadius: 6,
  },
  longPressBadgeText: {
    color: SEEKBAR_COLORS.PRIMARY_BLUE,
    fontSize: 8.5,
    fontWeight: '700',
    letterSpacing: 0.3,
  },
  skipControlsGroup: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  skipButton: {
    backgroundColor: colors.seekBarActionButton,
    borderColor: SEEKBAR_COLORS.PRIMARY_BLUE,
    borderWidth: 1,
    paddingHorizontal: 7,
    paddingVertical: 3,
    borderRadius: 7,
  },
  skipButtonFocused: {
    backgroundColor: SEEKBAR_COLORS.PRIMARY_BLUE,
    borderColor: SEEKBAR_COLORS.WHITE,
    transform: [{scale: 1.05}],
  },
  skipButtonText: {
    color: SEEKBAR_COLORS.WHITE,
    fontSize: 9,
    fontWeight: '700',
  },
  liveBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(229, 9, 20, 0.2)',
    borderColor: colors.heroAccent,
    borderWidth: 1,
    borderRadius: 6,
    paddingHorizontal: 6,
    paddingVertical: 2,
    marginLeft: 8,
    gap: 3,
  },
  liveDot: {
    width: 5,
    height: 5,
    borderRadius: 2.5,
    backgroundColor: colors.heroAccent,
  },
  liveBadgeText: {
    color: SEEKBAR_COLORS.WHITE,
    fontSize: 9,
    fontWeight: '800',
    letterSpacing: 0.5,
  },
  liveInfoContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  liveTimeText: {
    color: colors.heroAccent,
    fontSize: 10,
    fontWeight: '700',
    letterSpacing: 0.5,
    marginLeft: 5,
  },
  liveBar: {
    height: SEEKBAR_HEIGHT,
  },
  liveThumb: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: colors.heroAccent,
    borderWidth: 1.5,
    borderColor: SEEKBAR_COLORS.WHITE,
  },
  liveBroadcastTag: {
    backgroundColor: 'rgba(229, 9, 20, 0.15)',
    borderColor: colors.heroAccent,
    borderWidth: 1,
    paddingHorizontal: 6,
    paddingVertical: 2.5,
    borderRadius: 6,
  },
  liveBroadcastText: {
    color: colors.heroAccent,
    fontSize: 8.5,
    fontWeight: '700',
    letterSpacing: 0.5,
  },
  belowLabel: {
    position: 'absolute',
    height: 16,
    width: 44,
    borderRadius: 8,
    top: 16,
    backgroundColor: SEEKBAR_COLORS.SEGMENT_BLUE_1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  belowLabelText: {
    color: SEEKBAR_COLORS.WHITE,
    fontSize: 8.5,
    fontWeight: '700',
    letterSpacing: 0.4,
  },
  thumbnailBadge: {
    backgroundColor: colors.seekBarLimitsBadge,
    borderColor: SEEKBAR_COLORS.PRIMARY_BLUE,
    borderWidth: 1,
    paddingHorizontal: 6,
    paddingVertical: 2.5,
    borderRadius: 6,
  },
  thumbnailBadgeText: {
    color: SEEKBAR_COLORS.PRIMARY_BLUE,
    fontSize: 8.5,
    fontWeight: '700',
    letterSpacing: 0.3,
  },
  quickPlaybackControls: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    marginLeft: 8,
  },
  quickActionButton: {
    backgroundColor: colors.seekBarActionButton,
    borderColor: SEEKBAR_COLORS.PRIMARY_BLUE,
    borderWidth: 1,
    paddingHorizontal: 7,
    paddingVertical: 3,
    borderRadius: 7,
  },
  quickActionButtonFocused: {
    backgroundColor: SEEKBAR_COLORS.PRIMARY_BLUE,
    borderColor: SEEKBAR_COLORS.WHITE,
    transform: [{scale: 1.05}],
  },
  quickActionButtonText: {
    color: SEEKBAR_COLORS.WHITE,
    fontSize: 9,
    fontWeight: '700',
  },
  customDisablingBadge: {
    backgroundColor: colors.seekBarLimitsBadge,
    borderColor: SEEKBAR_COLORS.PRIMARY_BLUE,
    borderWidth: 1,
    paddingHorizontal: 6,
    paddingVertical: 2.5,
    borderRadius: 6,
  },
  customDisablingBadgeText: {
    color: SEEKBAR_COLORS.PRIMARY_BLUE,
    fontSize: 8.5,
    fontWeight: '700',
    letterSpacing: 0.3,
  },
  disablingPresetRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 3,
  },
  disablingPresetButton: {
    backgroundColor: colors.seekBarActionButton,
    borderColor: colors.controlBackground,
    borderWidth: 1,
    paddingHorizontal: 5,
    paddingVertical: 2,
    borderRadius: 5,
  },
  disablingPresetButtonActive: {
    backgroundColor: colors.seekBarTypePil,
    borderColor: SEEKBAR_COLORS.PRIMARY_BLUE,
  },
  disablingPresetButtonFocused: {
    backgroundColor: SEEKBAR_COLORS.PRIMARY_BLUE,
    borderColor: SEEKBAR_COLORS.WHITE,
    transform: [{scale: 1.05}],
  },
  disablingPresetButtonText: {
    color: SEEKBAR_COLORS.MEDIUM_GREY,
    fontSize: 8,
    fontWeight: '700',
  },
  disablingPresetButtonTextActive: {
    color: SEEKBAR_COLORS.WHITE,
  },
  toggleButton: {
    paddingHorizontal: 6,
    paddingVertical: 3,
    borderRadius: 7,
    borderWidth: 1,
  },
  toggleButtonActive: {
    backgroundColor: 'rgba(229, 9, 20, 0.25)',
    borderColor: '#E50914',
  },
  toggleButtonInactive: {
    backgroundColor: 'rgba(70, 211, 105, 0.2)',
    borderColor: '#46D369',
  },
  toggleButtonFocused: {
    borderColor: SEEKBAR_COLORS.WHITE,
    transform: [{scale: 1.05}],
  },
  toggleButtonText: {
    color: SEEKBAR_COLORS.WHITE,
    fontSize: 8.5,
    fontWeight: '800',
    letterSpacing: 0.4,
  },
  toggleGroup: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 3,
    flexWrap: 'wrap',
  },
  actionTogglePill: {
    paddingHorizontal: 5,
    paddingVertical: 2,
    borderRadius: 5,
    borderWidth: 1,
  },
  actionTogglePillDisabled: {
    backgroundColor: 'rgba(229, 9, 20, 0.2)',
    borderColor: '#E50914',
  },
  actionTogglePillEnabled: {
    backgroundColor: 'rgba(70, 211, 105, 0.2)',
    borderColor: '#46D369',
  },
  actionTogglePillFocusedState: {
    backgroundColor: 'rgba(0, 168, 225, 0.3)',
    borderColor: SEEKBAR_COLORS.PRIMARY_BLUE,
  },
  actionTogglePillUnfocusedState: {
    backgroundColor: 'rgba(128, 128, 128, 0.2)',
    borderColor: SEEKBAR_COLORS.MEDIUM_GREY,
  },
  actionTogglePillFocused: {
    borderColor: SEEKBAR_COLORS.WHITE,
    transform: [{scale: 1.05}],
  },
  actionToggleText: {
    color: SEEKBAR_COLORS.WHITE,
    fontSize: 8,
    fontWeight: '700',
  },
});
