import {StyleSheet} from 'react-native';
import {colors} from '../../theme/colors';
import {fontSizes, fontWeights, lineHeights} from '../../theme/fonts';
import {borderRadius, sizes, spacing} from '../../theme/sizes';

export const styles = StyleSheet.create({
  overlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: colors.overlayDark,
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 1000,
  },
  modalCard: {
    width: 640,
    maxHeight: 700,
    backgroundColor: colors.dialogBackground,
    borderRadius: borderRadius.dialog,
    borderWidth: spacing.borderThick,
    borderColor: colors.cardBorder,
    padding: spacing.xxl,
    alignItems: 'center',
    shadowColor: colors.shadowDark,
    shadowOffset: {width: 0, height: spacing.lg},
    shadowOpacity: 0.7,
    shadowRadius: spacing.xlarge,
  },
  header: {
    alignItems: 'center',
    marginBottom: spacing.xl,
  },
  iconBadge: {
    backgroundColor: colors.heroAccent,
    paddingHorizontal: spacing.xl,
    paddingVertical: spacing.xs,
    borderRadius: borderRadius.sm,
    marginBottom: spacing.sm,
  },
  iconBadgeText: {
    color: colors.textPrimary,
    fontSize: fontSizes.cardBadge,
    fontWeight: fontWeights.extraBold,
    letterSpacing: 1.5,
  },
  title: {
    color: colors.textPrimary,
    fontSize: fontSizes.subheading,
    fontWeight: fontWeights.extraBold,
    marginBottom: spacing.xxs,
    textAlign: 'center',
  },
  subtitle: {
    color: colors.textSecondary,
    fontSize: fontSizes.caption,
    lineHeight: lineHeights.dialogBody,
    textAlign: 'center',
    paddingHorizontal: spacing.md,
  },
  qualityListContainer: {
    width: '100%',
    maxHeight: 400,
    marginBottom: spacing.xl,
  },
  qualityListContent: {
    gap: spacing.sm,
    paddingVertical: spacing.xs,
  },
  qualityButton: {
    width: '100%',
    minHeight: 56,
    backgroundColor: colors.cardBorder,
    borderRadius: borderRadius.lg,
    borderWidth: spacing.borderThick,
    borderColor: colors.transparent,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.sm,
  },
  qualityButtonFocused: {
    borderColor: colors.focusRing,
    backgroundColor: colors.controlFocusedBackground,
  },
  qualityButtonSelected: {
    backgroundColor: 'rgba(229, 9, 20, 0.22)',
    borderColor: 'rgba(229, 9, 20, 0.6)',
  },
  qualityInfoRow: {
    flexDirection: 'row',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: spacing.sm,
    flex: 1,
  },
  qualityLabel: {
    color: colors.textPrimary,
    fontSize: fontSizes.body,
    fontWeight: fontWeights.boldWeight,
  },
  qualityLabelSelected: {
    color: colors.textPrimary,
    fontWeight: fontWeights.extraBold,
  },
  resolutionBadge: {
    backgroundColor: 'rgba(255, 255, 255, 0.12)',
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xxs,
    borderRadius: borderRadius.xs,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.2)',
  },
  resolutionBadgeText: {
    color: colors.textPrimary,
    fontSize: fontSizes.cardBadge,
    fontWeight: fontWeights.semibold,
    letterSpacing: 0.5,
  },
  bitrateBadge: {
    backgroundColor: 'rgba(0, 173, 225, 0.2)',
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xxs,
    borderRadius: borderRadius.xs,
    borderWidth: 1,
    borderColor: 'rgba(0, 173, 225, 0.5)',
  },
  bitrateBadgeText: {
    color: '#00ADE1',
    fontSize: fontSizes.cardBadge,
    fontWeight: fontWeights.semibold,
  },
  selectedBadge: {
    backgroundColor: colors.heroAccent,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.xxs,
    borderRadius: borderRadius.xs,
  },
  selectedBadgeText: {
    color: colors.textPrimary,
    fontSize: fontSizes.cardBadge,
    fontWeight: fontWeights.boldWeight,
  },
  checkmark: {
    color: colors.heroAccent,
    fontSize: fontSizes.body,
    fontWeight: fontWeights.extraBold,
    marginLeft: spacing.sm,
  },
  closeButton: {
    height: sizes.dialogButtonHeight,
    minWidth: 160,
    paddingHorizontal: spacing.xxl,
    borderRadius: borderRadius.xl,
    backgroundColor: colors.cardBorder,
    borderWidth: spacing.borderThick,
    borderColor: colors.transparent,
    alignItems: 'center',
    justifyContent: 'center',
  },
  closeButtonFocused: {
    borderColor: colors.textPrimary,
    backgroundColor: colors.heroAccent,
    transform: [{scale: 1.04}],
  },
  closeButtonText: {
    color: colors.textPrimary,
    fontSize: fontSizes.caption,
    fontWeight: fontWeights.boldWeight,
  },
});
