import {StyleSheet} from 'react-native';
import {colors} from '../../theme/colors';
import {fontSizes, fontWeights} from '../../theme/fonts';
import {borderRadius, sizes, spacing} from '../../theme/sizes';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.screenBackground,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: spacing.extraHuge,
    paddingVertical: spacing.huge,
  },
  backgroundImage: {
    flex: 1,
    width: '100%',
    height: '100%',
    justifyContent: 'center',
    alignItems: 'center',
  },
  card: {
    width: sizes.createProfileCardMaxWidth,
    maxHeight: '92%',
    backgroundColor: colors.modalCardBackground,
    borderRadius: borderRadius.dialog,
    borderWidth: spacing.borderMedium,
    borderColor: colors.cardBorder,
    paddingHorizontal: spacing.cardPadding,
    paddingVertical: spacing.colossal,
    shadowColor: colors.shadowDark,
    shadowOffset: {width: spacing.none, height: spacing.xl},
    shadowOpacity: 0.7,
    shadowRadius: spacing.huge,
  },
  header: {
    marginBottom: spacing.huge,
  },
  title: {
    color: colors.textPrimary,
    fontSize: fontSizes.userName,
    fontWeight: fontWeights.extraBold,
    marginBottom: spacing.sm,
  },
  subtitle: {
    color: colors.textSecondary,
    fontSize: fontSizes.caption,
  },
  errorBanner: {
    backgroundColor: colors.errorBackground,
    borderWidth: spacing.borderThin,
    borderColor: colors.errorText,
    borderRadius: borderRadius.md,
    paddingHorizontal: spacing.xxxl,
    paddingVertical: spacing.lg,
    marginBottom: spacing.xxxl,
  },
  errorText: {
    color: colors.errorText,
    fontSize: fontSizes.caption,
    fontWeight: fontWeights.semibold,
  },
  limitBanner: {
    backgroundColor: colors.warningBackground,
    borderWidth: spacing.borderThin,
    borderColor: colors.warningBorder,
    borderRadius: borderRadius.lg,
    padding: spacing.xlarge,
    alignItems: 'center',
    marginVertical: spacing.xlarge,
  },
  limitText: {
    color: colors.warningText,
    fontSize: fontSizes.body,
    fontWeight: fontWeights.semibold,
    textAlign: 'center',
    marginBottom: spacing.xxxl,
  },
  formContent: {
    gap: spacing.xxxl,
  },
  fieldGroup: {
    marginBottom: spacing.md,
  },
  labelRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: spacing.md,
  },
  label: {
    color: colors.textSecondary,
    fontSize: fontSizes.small,
    fontWeight: fontWeights.boldWeight,
    textTransform: 'uppercase',
    letterSpacing: 0.8,
  },
  charCount: {
    color: colors.textSecondary,
    fontSize: fontSizes.genre,
  },
  input: {
    height: sizes.createProfileInputHeight,
    backgroundColor: colors.inputBackground,
    borderRadius: borderRadius.lg,
    borderWidth: spacing.borderThick,
    borderColor: colors.chipBackground,
    paddingHorizontal: spacing.large,
    color: colors.textPrimary,
    fontSize: fontSizes.button,
  },
  inputFocused: {
    borderColor: colors.textPrimary,
    backgroundColor: colors.inputFocusedAltBackground,
  },
  toggleCard: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: colors.cardBackgroundSubtle,
    borderRadius: borderRadius.xl,
    borderWidth: spacing.borderThick,
    borderColor: colors.transparent,
    paddingHorizontal: spacing.xlarge,
    paddingVertical: spacing.xxl,
    marginVertical: spacing.sm,
  },
  toggleCardFocused: {
    borderColor: colors.textPrimary,
    backgroundColor: colors.inputFocusedAltBackground,
    transform: [{scale: 1.02}],
  },
  toggleCopy: {
    flex: 1,
    marginRight: spacing.xxxl,
  },
  toggleLabel: {
    color: colors.textPrimary,
    fontSize: fontSizes.body,
    fontWeight: fontWeights.boldWeight,
    marginBottom: spacing.xs,
  },
  toggleHint: {
    color: colors.textSecondary,
    fontSize: fontSizes.small,
  },
  switchTrack: {
    width: sizes.createProfileSwitchTrackWidth,
    height: sizes.createProfileSwitchTrackHeight,
    borderRadius: borderRadius.pill,
    backgroundColor: colors.controlBackground,
    padding: spacing.radiusTiny,
    justifyContent: 'center',
  },
  switchTrackEnabled: {
    backgroundColor: colors.kidsGreen,
  },
  switchThumb: {
    width: sizes.createProfileSwitchThumbSize,
    height: sizes.createProfileSwitchThumbSize,
    borderRadius: sizes.createProfileSwitchThumbRadius,
    backgroundColor: colors.textPrimary,
  },
  switchThumbEnabled: {
    alignSelf: 'flex-end',
  },
  actionsRow: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    gap: spacing.xxxl,
    marginTop: spacing.xlarge,
  },
  cancelButton: {
    paddingHorizontal: spacing.giant,
    height: sizes.createProfileInputHeight,
    borderRadius: borderRadius.lg,
    backgroundColor: colors.buttonSecondaryBackground,
    borderWidth: spacing.borderThick,
    borderColor: colors.transparent,
    alignItems: 'center',
    justifyContent: 'center',
  },
  cancelButtonFocused: {
    borderColor: colors.textPrimary,
    backgroundColor: colors.buttonSecondaryFocusedBackground,
    transform: [{scale: 1.04}],
  },
  cancelButtonText: {
    color: colors.textPrimary,
    fontSize: fontSizes.body,
    fontWeight: fontWeights.boldWeight,
  },
  createButton: {
    paddingHorizontal: spacing.section,
    height: sizes.createProfileInputHeight,
    borderRadius: borderRadius.lg,
    backgroundColor: colors.heroAccent,
    borderWidth: spacing.borderThick,
    borderColor: colors.transparent,
    alignItems: 'center',
    justifyContent: 'center',
  },
  createButtonFocused: {
    borderColor: colors.textPrimary,
    transform: [{scale: 1.04}],
    shadowColor: colors.heroAccent,
    shadowOffset: {width: spacing.none, height: spacing.xs},
    shadowOpacity: 0.6,
    shadowRadius: spacing.lg,
  },
  createButtonDisabled: {
    opacity: 0.5,
  },
  createButtonText: {
    color: colors.textPrimary,
    fontSize: fontSizes.body,
    fontWeight: fontWeights.extraBold,
  },
  maturityGroup: {
    marginVertical: spacing.sm,
  },
  maturityGrid: {
    flexDirection: 'row',
    gap: spacing.md,
    marginTop: spacing.xs,
  },
  maturityOption: {
    flex: 1,
    paddingVertical: spacing.md,
    paddingHorizontal: spacing.xs,
    backgroundColor: colors.inputBackground,
    borderRadius: borderRadius.lg,
    borderWidth: spacing.borderThick,
    borderColor: colors.chipBackground,
    alignItems: 'center',
    justifyContent: 'center',
  },
  maturityOptionSelected: {
    borderColor: colors.heroAccent,
    backgroundColor: colors.inputFocusedAltBackground,
  },
  maturityOptionFocused: {
    borderColor: colors.textPrimary,
    transform: [{scale: 1.04}],
  },
  maturityOptionText: {
    color: colors.textPrimary,
    fontSize: fontSizes.small,
    fontWeight: fontWeights.boldWeight,
    textAlign: 'center',
  },
  maturityOptionAge: {
    color: colors.heroAccent,
    fontSize: fontSizes.caption,
    fontWeight: fontWeights.semibold,
    marginTop: spacing.xxs,
  },
});
