import {StyleSheet} from 'react-native';
import {colors} from '../../theme/colors';
import {fontSizes, fontWeights, lineHeights} from '../../theme/fonts';
import {borderRadius, sizes, spacing} from '../../theme/sizes';

export const styles = StyleSheet.create({
  cardContainer: {
    alignItems: 'center',
    marginHorizontal: spacing.xxxl,
    marginVertical: spacing.xl,
  },
  card: {
    width: sizes.profileCardWidth,
    height: sizes.profileCardHeight,
    borderRadius: borderRadius.card,
    backgroundColor: colors.cardBackgroundSubtle,
    borderWidth: spacing.borderExtraThick,
    borderColor: colors.transparent,
    alignItems: 'center',
    justifyContent: 'center',
    padding: spacing.xxxl,
    transform: [{scale: 1}],
  },
  cardFocused: {
    borderColor: colors.textPrimary,
    backgroundColor: colors.inputFocusedBackground,
    transform: [{scale: 1.08}],
    shadowColor: colors.textPrimary,
    shadowOffset: {width: spacing.none, height: spacing.sm},
    shadowOpacity: 0.35,
    shadowRadius: spacing.xl,
    elevation: spacing.md,
  },
  cardActive: {
    borderColor: colors.heroAccent,
  },
  avatarWrapper: {
    width: sizes.profileAvatarWrapperSize,
    height: sizes.profileAvatarWrapperSize,
    borderRadius: sizes.profileAvatarWrapperRadius,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: spacing.xxxl,
    borderWidth: spacing.borderHeavy,
    position: 'relative',
    overflow: 'hidden',
  },
  avatarInner: {
    width: sizes.profileAvatarInnerSize,
    height: sizes.profileAvatarInnerSize,
    borderRadius: sizes.profileAvatarInnerRadius,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: spacing.borderMedium,
  },
  monogram: {
    color: colors.textPrimary,
    fontSize: fontSizes.monogram,
    fontWeight: fontWeights.extraBold,
    letterSpacing: spacing.borderThin,
  },
  kidsBadge: {
    position: 'absolute',
    top: spacing.md,
    right: spacing.xs,
    backgroundColor: colors.kidsGreen,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.radiusTiny,
    marginRight: spacing.xlarge,
    borderRadius: borderRadius.md,
    borderWidth: spacing.borderThin,
    borderColor: colors.kidsGreenBorder,
  },
  kidsBadgeText: {
    color: colors.textPrimary,
    fontSize: fontSizes.portraitBadge,
    fontWeight: fontWeights.black,
    letterSpacing: 0.8,
  },
  profileName: {
    color: colors.textPrimary,
    fontSize: fontSizes.cardTitle,
    fontWeight: fontWeights.boldWeight,
    textAlign: 'center',
    maxWidth: sizes.profileCardMaxWidth,
  },
  profileNameFocused: {
    color: colors.textPrimary,
    fontWeight: fontWeights.extraBold,
  },
  activeIndicator: {
    marginTop: spacing.sm,
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.xxs,
    borderRadius: borderRadius.lg,
    backgroundColor: colors.activeIndicatorBackground,
    borderWidth: spacing.borderThin,
    borderColor: colors.heroAccent,
  },
  activeIndicatorText: {
    color: colors.activeIndicatorText,
    fontSize: fontSizes.rating,
    fontWeight: fontWeights.semibold,
  },
  // Add Profile Card Variant
  addCard: {
    width: sizes.profileCardWidth,
    height: sizes.profileCardHeight,
    borderRadius: borderRadius.card,
    backgroundColor: colors.cardBackgroundMuted,
    borderWidth: spacing.borderExtraThick,
    borderColor: colors.cardBorderSubtle,
    borderStyle: 'dashed',
    alignItems: 'center',
    justifyContent: 'center',
    padding: spacing.xxxl,
  },
  addCardFocused: {
    borderColor: colors.textPrimary,
    backgroundColor: colors.inputFocusedBackground,
    borderStyle: 'solid',
    transform: [{scale: 1.08}],
    shadowColor: colors.textPrimary,
    shadowOffset: {width: spacing.none, height: spacing.sm},
    shadowOpacity: 0.35,
    shadowRadius: spacing.xl,
    elevation: spacing.md,
  },
  addIconWrapper: {
    width: sizes.profileAddIconWrapperSize,
    height: sizes.profileAddIconWrapperSize,
    borderRadius: sizes.profileAddIconWrapperRadius,
    backgroundColor: colors.inputBackground,
    borderWidth: spacing.borderThick,
    borderColor: colors.controlBackground,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: spacing.xxxl,
  },
  addIconText: {
    color: colors.textPrimary,
    fontSize: fontSizes.addIcon,
    lineHeight: lineHeights.addIcon,
    fontWeight: fontWeights.light,
    textAlign: 'center',
  },
  addLabel: {
    color: colors.textSecondary,
    fontSize: fontSizes.button,
    fontWeight: fontWeights.semibold,
    textAlign: 'center',
  },
  addLabelFocused: {
    color: colors.textPrimary,
    fontWeight: fontWeights.boldWeight,
  },
});
